#!/usr/bin/env sh

OPTIND=1
dflags=
d3flags=
usage='usage: diff3 [-3aEeXx] file1 file2 file3'

while getopts "aeExX3" c; do
	case "$c" in
	a)
		dflags="$dflags -$c"
		;;
	e|E|x|X|3)
		d3flags="-$c"
		;;
	*)
		echo "$usage" >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

if [ "$#" -lt 3 ]; then
	echo "$usage" >&2
	exit 1
fi

tmp1=$(mktemp -t d3a.XXXXXXXXXX) || exit 1
tmp2=$(mktemp -t d3b.XXXXXXXXXX)
if [ "$?" -ne 0 ]; then
	rm -f "$tmp1"
	exit 1
fi

cleanup() {
	rm -f "$tmp1" "$tmp2"
}
trap cleanup 0 1 2 13 15

diff $dflags -- "$1" "$3" > "$tmp1"
diff $dflags -- "$2" "$3" > "$tmp2"

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
exec "$dir/../libexec/diff3prog" $d3flags -- "$tmp1" "$tmp2" "$1" "$2" "$3"
