/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_LOGIN_CAP_H
#define MIXTAR_BRIDGE_LOGIN_CAP_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <pwd.h>

#include <stdlib.h>

#define LOGIN_DEFCLASS "default"

#define LOGIN_DEFSTYLE "passwd"

#define LOGIN_DEFSERVICE "login"

#define LOGIN_DEFUMASK 022

#define _PATH_LOGIN_CONF "/etc/login.conf"

#define _PATH_LOGIN_CONF_D "/etc/login.conf.d"

#define LOGIN_SETGROUP 0x0001

#define LOGIN_SETLOGIN 0x0002

#define LOGIN_SETPATH 0x0004

#define LOGIN_SETPRIORITY 0x0008

#define LOGIN_SETRESOURCES 0x0010

#define LOGIN_SETUMASK 0x0020

#define LOGIN_SETUSER 0x0040

#define LOGIN_SETENV 0x0080

#define LOGIN_SETRTABLE 0x0100

#define LOGIN_SETXDGENV 0x0200

#define LOGIN_SETALL 0x01ff

#ifndef QUAD_MIN
#define QUAD_MIN INT64_MIN
#endif

#define pw_class pw_gecos

typedef struct login_cap login_cap_t;

struct login_cap {
    char * lc_class;
    char * lc_cap;
    char * lc_style;
};

login_cap_t * login_getclass(char * class_name);

void login_close(login_cap_t * lc);

int login_getcapbool(login_cap_t * lc, char * cap, unsigned int def);

quad_t login_getcapnum(login_cap_t * lc, char * cap, quad_t def, quad_t error);

quad_t login_getcapsize(login_cap_t * lc, char * cap, quad_t def, quad_t error);

char * login_getcapstr(login_cap_t * lc, char * cap, char * def, char * error);

quad_t login_getcaptime(login_cap_t * lc, char * cap, quad_t def, quad_t error);

char * login_getstyle(login_cap_t * lc, char * style, char * type);

int setclasscontext(char * class_name, unsigned int flags);

int setusercontext(login_cap_t * lc, struct passwd * pwd, uid_t uid, unsigned int flags);

#endif /* MIXTAR_BRIDGE_LOGIN_CAP_H */
