/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_VIS_H
#define MIXTAR_BRIDGE_VIS_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <errno.h>

#include <ctype.h>

#include <stdlib.h>

#include <string.h>

#define VIS_OCTAL 0x0001

#define VIS_CSTYLE 0x0002

#define VIS_SP 0x0004

#define VIS_TAB 0x0008

#define VIS_NL 0x0010

#define VIS_WHITE VIS_SP | VIS_TAB | VIS_NL

#define VIS_SAFE 0x0020

#define VIS_NOSLASH 0x0040

#define VIS_HTTPSTYLE 0x0080

#define VIS_GLOB 0x0100

#define VIS_SHELL 0x0200

#define VIS_META 0x0400

#define VIS_NOLOCALE 0x0800

#define VIS_ALL 0x1000

#define UNVIS_VALID 1

#define UNVIS_VALIDPUSH 2

#define UNVIS_NOCHAR 3

#define UNVIS_SYNBAD -1

#define UNVIS_ERROR -2

#define UNVIS_END 1

char * vis(char * dst, int c, int flag, int nextc);

int strvis(char * dst, const char * src, int flag);

int strnvis(char * dst, const char * src, size_t dstlen, int flag);

int strvisx(char * dst, const char * src, size_t srclen, int flag);

int strnvisx(char * dst, const char * src, size_t srclen, size_t dstlen, int flag);

int stravis(char ** out, const char * src, int flag);

int stravisx(char ** out, const char * src, size_t srclen, int flag);

int strunvis(char * dst, const char * src);

int strnunvis(char * dst, const char * src, size_t dstlen);

int unvis(char * cp, int c, int * astate, int flag);

#define mbsavis(out, src, flag) stravis((out), (src), (flag))

#endif /* MIXTAR_BRIDGE_VIS_H */
