/* Generated by tools/cbind_probe.py. Do not edit by hand. */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/mman.h>
#include <wayland-client.h>
#include "generated/wayland/xdg-shell-client-protocol.h"

#include "generated/wayland/xdg-shell-protocol.c"

typedef struct wl_keyboard_listener wl_keyboard_listener;
typedef struct wl_pointer_listener wl_pointer_listener;
typedef struct wl_registry_listener wl_registry_listener;
typedef struct wl_seat_listener wl_seat_listener;
typedef struct xdg_surface_listener xdg_surface_listener;
typedef struct xdg_toplevel_listener xdg_toplevel_listener;
typedef struct xdg_wm_base_listener xdg_wm_base_listener;

_Static_assert((long long)(WL_KEYBOARD_KEY_STATE_PRESSED) == 1LL, "AIL_WAYLAND_KEYBOARD_KEY_PRESSED macro drift");
_Static_assert((long long)(WL_KEYBOARD_KEY_STATE_RELEASED) == 0LL, "AIL_WAYLAND_KEYBOARD_KEY_RELEASED macro drift");
_Static_assert((long long)(MAP_SHARED) == 1LL, "AIL_WAYLAND_MAP_SHARED macro drift");
_Static_assert((long long)(WL_POINTER_BUTTON_STATE_PRESSED) == 1LL, "AIL_WAYLAND_POINTER_BUTTON_PRESSED macro drift");
_Static_assert((long long)(WL_POINTER_BUTTON_STATE_RELEASED) == 0LL, "AIL_WAYLAND_POINTER_BUTTON_RELEASED macro drift");
_Static_assert((long long)(PROT_READ) == 1LL, "AIL_WAYLAND_PROT_READ macro drift");
_Static_assert((long long)(PROT_WRITE) == 2LL, "AIL_WAYLAND_PROT_WRITE macro drift");
_Static_assert((long long)(WL_SEAT_CAPABILITY_KEYBOARD) == 2LL, "AIL_WAYLAND_SEAT_CAP_KEYBOARD macro drift");
_Static_assert((long long)(WL_SEAT_CAPABILITY_POINTER) == 1LL, "AIL_WAYLAND_SEAT_CAP_POINTER macro drift");
_Static_assert((long long)(WL_SHM_FORMAT_ARGB8888) == 0LL, "AIL_WAYLAND_SHM_FORMAT_ARGB8888 macro drift");
_Static_assert((long long)(WL_SHM_FORMAT_XRGB8888) == 1LL, "AIL_WAYLAND_SHM_FORMAT_XRGB8888 macro drift");

_Static_assert(sizeof(struct wl_keyboard_listener) == 48u, "wl_keyboard_listener size drift");
_Static_assert(_Alignof(struct wl_keyboard_listener) == 8u, "wl_keyboard_listener align drift");
_Static_assert(offsetof(struct wl_keyboard_listener, enter) == 8u, "wl_keyboard_listener.enter offset drift");
_Static_assert(sizeof(((struct wl_keyboard_listener*)0)->enter) == 8u, "wl_keyboard_listener.enter size drift");
_Static_assert(offsetof(struct wl_keyboard_listener, key) == 24u, "wl_keyboard_listener.key offset drift");
_Static_assert(sizeof(((struct wl_keyboard_listener*)0)->key) == 8u, "wl_keyboard_listener.key size drift");
_Static_assert(offsetof(struct wl_keyboard_listener, keymap) == 0u, "wl_keyboard_listener.keymap offset drift");
_Static_assert(sizeof(((struct wl_keyboard_listener*)0)->keymap) == 8u, "wl_keyboard_listener.keymap size drift");
_Static_assert(offsetof(struct wl_keyboard_listener, leave) == 16u, "wl_keyboard_listener.leave offset drift");
_Static_assert(sizeof(((struct wl_keyboard_listener*)0)->leave) == 8u, "wl_keyboard_listener.leave size drift");
_Static_assert(offsetof(struct wl_keyboard_listener, modifiers) == 32u, "wl_keyboard_listener.modifiers offset drift");
_Static_assert(sizeof(((struct wl_keyboard_listener*)0)->modifiers) == 8u, "wl_keyboard_listener.modifiers size drift");
_Static_assert(offsetof(struct wl_keyboard_listener, repeat_info) == 40u, "wl_keyboard_listener.repeat_info offset drift");
_Static_assert(sizeof(((struct wl_keyboard_listener*)0)->repeat_info) == 8u, "wl_keyboard_listener.repeat_info size drift");

_Static_assert(sizeof(struct wl_pointer_listener) == 88u, "wl_pointer_listener size drift");
_Static_assert(_Alignof(struct wl_pointer_listener) == 8u, "wl_pointer_listener align drift");
_Static_assert(offsetof(struct wl_pointer_listener, axis) == 32u, "wl_pointer_listener.axis offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->axis) == 8u, "wl_pointer_listener.axis size drift");
_Static_assert(offsetof(struct wl_pointer_listener, axis_discrete) == 64u, "wl_pointer_listener.axis_discrete offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->axis_discrete) == 8u, "wl_pointer_listener.axis_discrete size drift");
_Static_assert(offsetof(struct wl_pointer_listener, axis_relative_direction) == 80u, "wl_pointer_listener.axis_relative_direction offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->axis_relative_direction) == 8u, "wl_pointer_listener.axis_relative_direction size drift");
_Static_assert(offsetof(struct wl_pointer_listener, axis_source) == 48u, "wl_pointer_listener.axis_source offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->axis_source) == 8u, "wl_pointer_listener.axis_source size drift");
_Static_assert(offsetof(struct wl_pointer_listener, axis_stop) == 56u, "wl_pointer_listener.axis_stop offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->axis_stop) == 8u, "wl_pointer_listener.axis_stop size drift");
_Static_assert(offsetof(struct wl_pointer_listener, axis_value120) == 72u, "wl_pointer_listener.axis_value120 offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->axis_value120) == 8u, "wl_pointer_listener.axis_value120 size drift");
_Static_assert(offsetof(struct wl_pointer_listener, button) == 24u, "wl_pointer_listener.button offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->button) == 8u, "wl_pointer_listener.button size drift");
_Static_assert(offsetof(struct wl_pointer_listener, enter) == 0u, "wl_pointer_listener.enter offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->enter) == 8u, "wl_pointer_listener.enter size drift");
_Static_assert(offsetof(struct wl_pointer_listener, frame) == 40u, "wl_pointer_listener.frame offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->frame) == 8u, "wl_pointer_listener.frame size drift");
_Static_assert(offsetof(struct wl_pointer_listener, leave) == 8u, "wl_pointer_listener.leave offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->leave) == 8u, "wl_pointer_listener.leave size drift");
_Static_assert(offsetof(struct wl_pointer_listener, motion) == 16u, "wl_pointer_listener.motion offset drift");
_Static_assert(sizeof(((struct wl_pointer_listener*)0)->motion) == 8u, "wl_pointer_listener.motion size drift");

_Static_assert(sizeof(struct wl_registry_listener) == 16u, "wl_registry_listener size drift");
_Static_assert(_Alignof(struct wl_registry_listener) == 8u, "wl_registry_listener align drift");
_Static_assert(offsetof(struct wl_registry_listener, global) == 0u, "wl_registry_listener.global offset drift");
_Static_assert(sizeof(((struct wl_registry_listener*)0)->global) == 8u, "wl_registry_listener.global size drift");
_Static_assert(offsetof(struct wl_registry_listener, global_remove) == 8u, "wl_registry_listener.global_remove offset drift");
_Static_assert(sizeof(((struct wl_registry_listener*)0)->global_remove) == 8u, "wl_registry_listener.global_remove size drift");

_Static_assert(sizeof(struct wl_seat_listener) == 16u, "wl_seat_listener size drift");
_Static_assert(_Alignof(struct wl_seat_listener) == 8u, "wl_seat_listener align drift");
_Static_assert(offsetof(struct wl_seat_listener, capabilities) == 0u, "wl_seat_listener.capabilities offset drift");
_Static_assert(sizeof(((struct wl_seat_listener*)0)->capabilities) == 8u, "wl_seat_listener.capabilities size drift");
_Static_assert(offsetof(struct wl_seat_listener, name) == 8u, "wl_seat_listener.name offset drift");
_Static_assert(sizeof(((struct wl_seat_listener*)0)->name) == 8u, "wl_seat_listener.name size drift");

_Static_assert(sizeof(struct xdg_surface_listener) == 8u, "xdg_surface_listener size drift");
_Static_assert(_Alignof(struct xdg_surface_listener) == 8u, "xdg_surface_listener align drift");
_Static_assert(offsetof(struct xdg_surface_listener, configure) == 0u, "xdg_surface_listener.configure offset drift");
_Static_assert(sizeof(((struct xdg_surface_listener*)0)->configure) == 8u, "xdg_surface_listener.configure size drift");

_Static_assert(sizeof(struct xdg_toplevel_listener) == 32u, "xdg_toplevel_listener size drift");
_Static_assert(_Alignof(struct xdg_toplevel_listener) == 8u, "xdg_toplevel_listener align drift");
_Static_assert(offsetof(struct xdg_toplevel_listener, close) == 8u, "xdg_toplevel_listener.close offset drift");
_Static_assert(sizeof(((struct xdg_toplevel_listener*)0)->close) == 8u, "xdg_toplevel_listener.close size drift");
_Static_assert(offsetof(struct xdg_toplevel_listener, configure) == 0u, "xdg_toplevel_listener.configure offset drift");
_Static_assert(sizeof(((struct xdg_toplevel_listener*)0)->configure) == 8u, "xdg_toplevel_listener.configure size drift");
_Static_assert(offsetof(struct xdg_toplevel_listener, configure_bounds) == 16u, "xdg_toplevel_listener.configure_bounds offset drift");
_Static_assert(sizeof(((struct xdg_toplevel_listener*)0)->configure_bounds) == 8u, "xdg_toplevel_listener.configure_bounds size drift");
_Static_assert(offsetof(struct xdg_toplevel_listener, wm_capabilities) == 24u, "xdg_toplevel_listener.wm_capabilities offset drift");
_Static_assert(sizeof(((struct xdg_toplevel_listener*)0)->wm_capabilities) == 8u, "xdg_toplevel_listener.wm_capabilities size drift");

_Static_assert(sizeof(struct xdg_wm_base_listener) == 8u, "xdg_wm_base_listener size drift");
_Static_assert(_Alignof(struct xdg_wm_base_listener) == 8u, "xdg_wm_base_listener align drift");
_Static_assert(offsetof(struct xdg_wm_base_listener, ping) == 0u, "xdg_wm_base_listener.ping offset drift");
_Static_assert(sizeof(((struct xdg_wm_base_listener*)0)->ping) == 8u, "xdg_wm_base_listener.ping size drift");

int32_t ail_c_strcmp(const char * left, const char * right) {
    return (int32_t)(strcmp(left, right));
}

int ail_wayland_memfd_create(const char * name, unsigned int flags) {
    return (int)(syscall(SYS_memfd_create, name, flags));
}

void ail_wl_buffer_destroy(void * buffer) {
    wl_buffer_destroy((struct wl_buffer *)buffer);
    return;
}

void * ail_wl_compositor_create_surface(void * compositor) {
    return (void *)(wl_compositor_create_surface((struct wl_compositor *)compositor));
}

void ail_wl_compositor_destroy(void * compositor) {
    wl_compositor_destroy((struct wl_compositor *)compositor);
    return;
}

void * ail_wl_display_connect_default(void) {
    return (void *)(wl_display_connect(NULL));
}

void ail_wl_display_disconnect(void * display) {
    wl_display_disconnect((struct wl_display *)display);
    return;
}

int32_t ail_wl_display_dispatch(void * display) {
    return (int32_t)(wl_display_dispatch((struct wl_display *)display));
}

int32_t ail_wl_display_dispatch_pending(void * display) {
    return (int32_t)(wl_display_dispatch_pending((struct wl_display *)display));
}

int32_t ail_wl_display_flush(void * display) {
    return (int32_t)(wl_display_flush((struct wl_display *)display));
}

void * ail_wl_display_get_registry(void * display) {
    return (void *)(wl_display_get_registry((struct wl_display *)display));
}

int32_t ail_wl_display_roundtrip(void * display) {
    return (int32_t)(wl_display_roundtrip((struct wl_display *)display));
}

int32_t ail_wl_keyboard_add_listener(void * keyboard, void * listener, void * data) {
    return (int32_t)(wl_keyboard_add_listener((struct wl_keyboard *)keyboard, (const struct wl_keyboard_listener *)listener, data));
}

void ail_wl_keyboard_release(void * keyboard) {
    wl_keyboard_release((struct wl_keyboard *)keyboard);
    return;
}

int32_t ail_wl_pointer_add_listener(void * pointer, void * listener, void * data) {
    return (int32_t)(wl_pointer_add_listener((struct wl_pointer *)pointer, (const struct wl_pointer_listener *)listener, data));
}

void ail_wl_pointer_release(void * pointer) {
    wl_pointer_release((struct wl_pointer *)pointer);
    return;
}

int32_t ail_wl_registry_add_listener(void * registry, void * listener, void * data) {
    return (int32_t)(wl_registry_add_listener((struct wl_registry *)registry, (const struct wl_registry_listener *)listener, data));
}

void * ail_wl_registry_bind_compositor(void * registry, uint32_t name, uint32_t version) {
    uint32_t use_version = version < 4u ? version : 4u;
    return (void *)wl_registry_bind((struct wl_registry *)registry, name, &wl_compositor_interface, use_version);
}

void * ail_wl_registry_bind_seat(void * registry, uint32_t name, uint32_t version) {
    uint32_t use_version = version < 9u ? version : 9u;
    return (void *)wl_registry_bind((struct wl_registry *)registry, name, &wl_seat_interface, use_version);
}

void * ail_wl_registry_bind_shm(void * registry, uint32_t name, uint32_t version) {
    uint32_t use_version = version < 1u ? version : 1u;
    return (void *)wl_registry_bind((struct wl_registry *)registry, name, &wl_shm_interface, use_version);
}

void * ail_wl_registry_bind_xdg_wm_base(void * registry, uint32_t name, uint32_t version) {
    uint32_t use_version = version < 6u ? version : 6u;
    return (void *)wl_registry_bind((struct wl_registry *)registry, name, &xdg_wm_base_interface, use_version);
}

void ail_wl_registry_destroy(void * registry) {
    wl_registry_destroy((struct wl_registry *)registry);
    return;
}

int32_t ail_wl_seat_add_listener(void * seat, void * listener, void * data) {
    return (int32_t)(wl_seat_add_listener((struct wl_seat *)seat, (const struct wl_seat_listener *)listener, data));
}

void * ail_wl_seat_get_keyboard(void * seat) {
    return (void *)(wl_seat_get_keyboard((struct wl_seat *)seat));
}

void * ail_wl_seat_get_pointer(void * seat) {
    return (void *)(wl_seat_get_pointer((struct wl_seat *)seat));
}

void ail_wl_seat_release(void * seat) {
    wl_seat_release((struct wl_seat *)seat);
    return;
}

void * ail_wl_shm_create_pool(void * shm, int32_t fd, int32_t size) {
    return (void *)(wl_shm_create_pool((struct wl_shm *)shm, fd, size));
}

void * ail_wl_shm_pool_create_buffer(void * pool, int32_t offset, int32_t width, int32_t height, int32_t stride, uint32_t format) {
    return (void *)(wl_shm_pool_create_buffer((struct wl_shm_pool *)pool, offset, width, height, stride, format));
}

void ail_wl_shm_pool_destroy(void * pool) {
    wl_shm_pool_destroy((struct wl_shm_pool *)pool);
    return;
}

void ail_wl_shm_release(void * shm) {
    wl_shm_release((struct wl_shm *)shm);
    return;
}

void ail_wl_surface_attach(void * surface, void * buffer, int32_t x, int32_t y) {
    wl_surface_attach((struct wl_surface *)surface, (struct wl_buffer *)buffer, x, y);
    return;
}

void ail_wl_surface_commit(void * surface) {
    wl_surface_commit((struct wl_surface *)surface);
    return;
}

void ail_wl_surface_damage_buffer(void * surface, int32_t x, int32_t y, int32_t width, int32_t height) {
    wl_surface_damage_buffer((struct wl_surface *)surface, x, y, width, height);
    return;
}

void ail_wl_surface_destroy(void * surface) {
    wl_surface_destroy((struct wl_surface *)surface);
    return;
}

void ail_xdg_surface_ack_configure(void * xdg_surface, uint32_t serial) {
    xdg_surface_ack_configure((struct xdg_surface *)xdg_surface, serial);
    return;
}

int32_t ail_xdg_surface_add_listener(void * xdg_surface, void * listener, void * data) {
    return (int32_t)(xdg_surface_add_listener((struct xdg_surface *)xdg_surface, (const struct xdg_surface_listener *)listener, data));
}

void ail_xdg_surface_destroy(void * xdg_surface) {
    xdg_surface_destroy((struct xdg_surface *)xdg_surface);
    return;
}

void * ail_xdg_surface_get_toplevel(void * xdg_surface) {
    return (void *)(xdg_surface_get_toplevel((struct xdg_surface *)xdg_surface));
}

int32_t ail_xdg_toplevel_add_listener(void * toplevel, void * listener, void * data) {
    return (int32_t)(xdg_toplevel_add_listener((struct xdg_toplevel *)toplevel, (const struct xdg_toplevel_listener *)listener, data));
}

void ail_xdg_toplevel_destroy(void * toplevel) {
    xdg_toplevel_destroy((struct xdg_toplevel *)toplevel);
    return;
}

void ail_xdg_toplevel_set_title(void * toplevel, const char * title) {
    xdg_toplevel_set_title((struct xdg_toplevel *)toplevel, title);
    return;
}

int32_t ail_xdg_wm_base_add_listener(void * wm_base, void * listener, void * data) {
    return (int32_t)(xdg_wm_base_add_listener((struct xdg_wm_base *)wm_base, (const struct xdg_wm_base_listener *)listener, data));
}

void ail_xdg_wm_base_destroy(void * wm_base) {
    xdg_wm_base_destroy((struct xdg_wm_base *)wm_base);
    return;
}

void * ail_xdg_wm_base_get_xdg_surface(void * wm_base, void * surface) {
    return (void *)(xdg_wm_base_get_xdg_surface((struct xdg_wm_base *)wm_base, (struct wl_surface *)surface));
}

void ail_xdg_wm_base_pong(void * wm_base, uint32_t serial) {
    xdg_wm_base_pong((struct xdg_wm_base *)wm_base, serial);
    return;
}
