"""
PrologueEmitter — service that emits the C-output prologue.

Replaces ``_EmitPrologueMixin``. Constructed once per compile with the
populated ``TypeInfo`` + ``RuntimeNeeds`` + the few CTranspiler helper
callables it needs (type-mapping, name-mangling, return-type
inference, param-formatting, class-new-signature). Methods emit the
header / includes / runtime preamble / type defs / forward decls /
template blocks / cinclude+link directives -- everything that lands in
the C output before user-function bodies.

Phase 7 of the New Path roadmap. The legacy mixin's ``_emit_runtime``
is replaced by an explicit call to ``RuntimeEmitter`` from the
``CTranspiler.transpile()`` orchestrator, so this service is purely
prologue.
"""

from __future__ import annotations

from parser import ast as A
from parser.ast import parsed_type_to_str
from typing import Any, Callable, List, Tuple

from abi_symbols import explicit_c_abi_parts
from callback_types import callback_parts, is_callback_type
from calling_conventions import c_callconv_macro, normalized_decorators
from target_info import os_from_platform, target_matches
from transpiler.class_field_ownership import (
    is_auto_owned_field_type,
    is_auto_owned_param,
    is_string_type,
    owned_field_flag_name,
    owned_param_flag_name,
    param_name,
    string_len_field_name,
    string_len_param_name,
)
from transpiler.fixed_array_types import parse_fixed_array_type_spec
from transpiler.runtime_needs import RuntimeNeeds
from transpiler.type_info import TypeInfo


class PrologueEmitter:
    """Emits the C output's pre-user-code section. Stateless apart
    from the data + callables it receives in __init__; ``self._indent``
    is fixed to 0 because the prologue is all top-level decls.
    """

    def __init__(
        self,
        type_info: TypeInfo,
        runtime_needs: RuntimeNeeds,
        user_defined_funcs: set,
        output: List[str],
        ailang_type_to_c: Callable[[str], str],
        mangle_name: Callable[[str], str],
        get_return_type: Callable[[Any], str],
        format_params: Callable[..., str],
        class_new_signature: Callable[[A.ClassDef], Tuple[str, List[str]]],
        format_declaration: Callable[[str, str], str] | None = None,
    ) -> None:
        self._type_info = type_info
        self._needs = runtime_needs
        self._user_defined_funcs = user_defined_funcs
        self._output = output
        self._ailang_type_to_c = ailang_type_to_c
        self._mangle_name = mangle_name
        self._get_return_type = get_return_type
        self._format_params = format_params
        self._class_new_signature = class_new_signature
        self._format_declaration = format_declaration

    def _parse_fixed_array_type_spec(self, atype: str) -> Tuple[str, int] | None:
        return parse_fixed_array_type_spec(parsed_type_to_str(atype))

    def _format_decl(self, atype: str, name: str) -> str:
        if self._format_declaration is not None:
            return self._format_declaration(atype, name)
        atype_str = parsed_type_to_str(atype)
        fixed = self._parse_fixed_array_type_spec(atype_str)
        if fixed is not None:
            elem_type, size = fixed
            return f"{self._ailang_type_to_c(elem_type)} {name}[{size}]"
        return f"{self._ailang_type_to_c(atype_str)} {name}"

    def _emit_header(self, source_file: str) -> None:
        """Emit C headers."""
        self._output.append("/*")
        self._output.append(" * Generated by AILang to C Transpiler")
        self._output.append(
            " * C23 (ISO/IEC 9899:2024) - compiles on Windows/Linux/macOS/BSD"
        )
        self._output.append(
            " * Compiles with: gcc -Wall -Wextra -Werror -pedantic -std=c23"
        )
        self._output.append(" * Safety: bounds checking, overflow detection, nullptr")
        if source_file:
            self._output.append(f" * Source: {source_file}")
        self._output.append(" */")
        self._output.append("")

        # Platform detection - works everywhere
        self._output.append("/* Platform detection */")
        self._output.append(
            "#if defined(_WIN32) || defined(_WIN64) || defined(__CYGWIN__)"
        )
        self._output.append("    #define AILANG_WINDOWS 1")
        self._output.append("#elif defined(__linux__)")
        self._output.append("    #define AILANG_LINUX 1")
        self._output.append("#elif defined(__APPLE__) && defined(__MACH__)")
        self._output.append("    #define AILANG_MACOS 1")
        bsd_check = "#elif defined(__FreeBSD__) || defined(__NetBSD__)"
        bsd_check += " || defined(__OpenBSD__) || defined(__DragonFly__)"
        self._output.append(bsd_check)
        self._output.append("    #define AILANG_BSD 1")
        self._output.append("#elif defined(__unix__) || defined(__unix)")
        self._output.append("    #define AILANG_UNIX 1")
        self._output.append("#else")
        self._output.append("    #define AILANG_FREESTANDING 1")
        self._output.append("#endif")
        self._output.append("")

        self._output.append("/* Calling convention portability */")
        self._output.append(
            "#if defined(_WIN32) || defined(_WIN64) || defined(__CYGWIN__)"
        )
        self._output.append("    #define AILANG_STDCALL __stdcall")
        self._output.append("    #define AILANG_FASTCALL __fastcall")
        self._output.append("#else")
        self._output.append("    #define AILANG_STDCALL")
        self._output.append("    #define AILANG_FASTCALL")
        self._output.append("#endif")
        self._output.append("")

        # Feature test macros MUST come before any includes
        if (
            "time_ns" in self._needs.helpers
            or "time_ms" in self._needs.helpers
            or "split" in self._needs.helpers
            or "split_ints" in self._needs.helpers
            or "process" in self._needs.helpers
            or "syscall" in self._needs.helpers
        ):
            self._output.append("/* Enable POSIX features on Unix-like systems */")
            self._output.append(
                "#if !defined(AILANG_WINDOWS) && !defined(AILANG_FREESTANDING)"
            )
            self._output.append("    #ifndef _POSIX_C_SOURCE")
            self._output.append("        #define _POSIX_C_SOURCE 200809L")
            self._output.append("    #endif")
            self._output.append("#endif")
            self._output.append("")

        # Standard headers (not included in freestanding)
        self._output.append("#ifndef AILANG_FREESTANDING")
        self._output.append("    #include <stdio.h>")
        self._output.append("    #include <stdlib.h>")
        self._output.append("    #include <stdint.h>")
        self._output.append("    #include <stddef.h>")
        self._output.append("    #include <string.h>")
        self._output.append("    #include <stdbool.h>")
        self._output.append("    #include <signal.h>")
        if "math" in self._needs.helpers:
            self._output.append("    #include <math.h>")
        # x86 intrinsics for __rdtsc (also pulled in implicitly by
        # <immintrin.h> on Windows, but we want it explicit).
        if "rdtsc" in self._needs.helpers:
            self._output.append(
                "    #if defined(__x86_64__) || defined(_M_X64)"
                " || defined(__i386__) || defined(_M_IX86)"
            )
            self._output.append("        #include <x86intrin.h>")
            self._output.append("    #endif")
        # C11 atomics (standard, portable)
        if self._needs.atomics:
            self._output.append("    #include <stdatomic.h>")
        if self._needs.exceptions:
            self._output.append("    #include <setjmp.h>")
        else:
            # Safety trap needs setjmp/longjmp even without explicit try/catch
            self._output.append("    #include <setjmp.h>")

        # Windows-only: <io.h> for _setmode/_fileno, <fcntl.h> for _O_BINARY.
        # Used by the binary-stdio shim emitted at the top of every main().
        # Cost on non-Windows: zero (the #if guard skips both headers).
        self._output.append(
            "    #if defined(_WIN32) || defined(_WIN64) || defined(__CYGWIN__)"
        )
        if "sockets" in self._needs.helpers:
            self._output.append("        #include <winsock2.h>")
        self._output.append("        #include <windows.h>")
        self._output.append("        #include <io.h>")
        self._output.append("        #include <fcntl.h>")
        self._output.append("    #endif")

        # Suppress unused warnings for conditionally-used helpers
        self._output.append("")
        self._output.append("    /* Suppress unused warnings for optional helpers */")
        self._output.append("    #ifdef __GNUC__")
        self._output.append("        #define AILANG_UNUSED __attribute__((unused))")
        self._output.append("    #else")
        self._output.append("        #define AILANG_UNUSED")
        self._output.append("    #endif")
        # Threading support. Prefer Win32 threads on Windows (MinGW gcc
        # claims C11 conformance but doesn't ship <threads.h>, so a
        # __STDC_VERSION__-based check picks the wrong path), then real
        # C11 where it exists, then pthread.
        if self._needs.threading or self._needs.channels or self._needs.sync:
            self._output.append(
                "    /* Threading support - Windows native first, then C11, then pthreads */"
            )
            self._output.append("    #if defined(_WIN32) || defined(__CYGWIN__)")
            # winsock2.h must precede windows.h. The order matters even
            # inside this guarded block because the preprocessor re-checks
            # the include guards and would emit the warning again.
            if "sockets" in self._needs.helpers:
                self._output.append("        #include <winsock2.h>")
            self._output.append("        #include <windows.h>")
            self._output.append("        #define AILANG_WIN_THREADS 1")
            self._output.append(
                "    #elif __STDC_VERSION__ >= 201112L && !defined(__STDC_NO_THREADS__)"
            )
            self._output.append("        #include <threads.h>")
            self._output.append("        #define AILANG_C11_THREADS 1")
            self._output.append("    #else")
            self._output.append("        #include <pthread.h>")
            self._output.append("        #define AILANG_PTHREADS 1")
            self._output.append("    #endif")
        self._output.append("#else")
        self._output.append("    /* Freestanding: provide minimal types */")
        self._output.append("    #ifdef __GNUC__")
        self._output.append("        #define AILANG_UNUSED __attribute__((unused))")
        self._output.append("    #else")
        self._output.append("        #define AILANG_UNUSED")
        self._output.append("    #endif")
        self._output.append("    typedef signed char int8_t;")
        self._output.append("    typedef short int16_t;")
        self._output.append("    typedef int int32_t;")
        self._output.append("    typedef long long int64_t;")
        self._output.append("    typedef unsigned char uint8_t;")
        self._output.append("    typedef unsigned short uint16_t;")
        self._output.append("    typedef unsigned int uint32_t;")
        self._output.append("    typedef unsigned long long uint64_t;")
        self._output.append("    #ifndef INT64_MAX")
        self._output.append("        #define INT64_MAX 9223372036854775807LL")
        self._output.append("    #endif")
        self._output.append("    #ifndef INT64_MIN")
        self._output.append("        #define INT64_MIN (-INT64_MAX - 1LL)")
        self._output.append("    #endif")
        self._output.append("    #ifndef UINT64_MAX")
        self._output.append("        #define UINT64_MAX 18446744073709551615ULL")
        self._output.append("    #endif")
        self._output.append("    #if defined(__SIZE_TYPE__)")
        self._output.append("        typedef __SIZE_TYPE__ size_t;")
        self._output.append("    #else")
        self._output.append("        typedef unsigned long long size_t;")
        self._output.append("    #endif")
        self._output.append("    #ifndef SIZE_MAX")
        self._output.append("        #define SIZE_MAX ((size_t)-1)")
        self._output.append("    #endif")
        self._output.append("    #if defined(__UINTPTR_TYPE__)")
        self._output.append("        typedef __UINTPTR_TYPE__ uintptr_t;")
        self._output.append("    #else")
        self._output.append("        typedef unsigned long long uintptr_t;")
        self._output.append("    #endif")
        self._output.append("    #ifndef NULL")
        self._output.append("        #define NULL ((void*)0)")
        self._output.append("    #endif")
        self._output.append(
            "    #if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 202000L"
        )
        self._output.append("        typedef _Bool bool;")
        self._output.append("        #define true 1")
        self._output.append("        #define false 0")
        self._output.append("    #endif")
        self._output.append(
            "    #if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 202311L"
        )
        self._output.append("        #define nullptr ((void*)0)")
        self._output.append("    #endif")
        self._output.append("#endif")
        self._output.append("")
        self._output.append(
            "/* C23 compatibility - use native nullptr when available. */"
        )
        self._output.append("#ifndef AILANG_FREESTANDING")
        self._output.append(
            "    #if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 202311L"
        )
        self._output.append("        #ifndef nullptr")
        self._output.append("            #define nullptr NULL")
        self._output.append("        #endif")
        self._output.append("    #endif")
        self._output.append("#endif")
        self._output.append("")

        # Array structure for arrays with length tracking (if needed)
        if self._needs.arrays:
            self._output.append("/* Array structure with length tracking */")
            self._output.append("typedef struct {")
            self._output.append("    int64_t *data;")
            self._output.append("    int64_t length;")
            self._output.append("} ailang_array;")
            self._output.append("")

        # Exception handling globals (setjmp/longjmp) — always emitted for safety trap
        self._output.append(
            "/* Exception handling state (used by safety trap + try/catch) */"
        )
        self._output.append("#ifndef AILANG_FREESTANDING")
        self._output.append("static jmp_buf __ailang_exc_jmpbuf;")
        self._output.append("#endif")
        self._output.append("AILANG_UNUSED static const char *__ailang_exc_msg = NULL;")
        self._output.append("AILANG_UNUSED static uint32_t __ailang_exc_type = 0;")
        self._output.append("")

        # Platform-specific headers
        if "time_ns" in self._needs.helpers or "time_ms" in self._needs.helpers:
            self._output.append("/* Platform-specific timing headers */")
            self._output.append("#ifdef AILANG_WINDOWS")
            # winsock2.h MUST be included before windows.h on MinGW/MSVC.
            # If sockets are also used by this program, pre-include it
            # here so the order holds across the whole TU.
            if "sockets" in self._needs.helpers:
                self._output.append("    #include <winsock2.h>")
            self._output.append("    #include <windows.h>")
            self._output.append("#elif defined(AILANG_MACOS)")
            self._output.append("    #include <mach/mach_time.h>")
            self._output.append("#elif !defined(AILANG_FREESTANDING)")
            self._output.append("    #include <time.h>")
            self._output.append("#endif")
            self._output.append("")

    def _emit_type_definitions(self) -> None:
        """Emit struct and enum definitions."""
        # Simple enums (no data-carrying variants)
        for name, variants in self._type_info.enums.items():
            if name not in self._type_info.data_enums:
                # Simple C-style enum
                self._output.append("typedef enum {")
                for vname, vval in variants:
                    self._output.append(f"    {name}_{vname} = {vval},")
                self._output.append("} " + name + ";")
                self._output.append("")

        # Data-carrying enums (tagged unions)
        for name, data_variants in self._type_info.data_enums.items():
            # First emit the tag enum
            self._output.append("typedef enum {")
            for vname, _ in self._type_info.enums[name]:
                self._output.append(f"    {name}_TAG_{vname},")
            self._output.append(f"}} {name}_Tag;")
            self._output.append("")

            # Emit structs for each variant with data
            for vname, fields in data_variants.items():
                self._output.append("typedef struct {")
                for fname, ftype in fields:
                    self._output.append(f"    {self._format_decl(ftype, fname)};")
                self._output.append(f"}} {name}_{vname}_Data;")
                self._output.append("")

            # Emit the tagged union struct
            self._output.append("typedef struct {")
            self._output.append(f"    {name}_Tag tag;")
            self._output.append("    union {")
            for vname, _ in self._type_info.enums[name]:
                if vname in data_variants:
                    self._output.append(f"        {name}_{vname}_Data {vname.lower()};")
            self._output.append("    } data;")
            self._output.append(f"}} {name};")
            self._output.append("")

        for name in sorted(self._type_info.opaque_records):
            c_name = self._type_info.extern_record_c_names.get(name, name)
            explicit = name in self._type_info.extern_record_c_name_explicit
            if c_name != name:
                self._output.append(f"typedef {c_name} {name};")
            elif explicit:
                self._output.append(f"/* extern record {name} uses existing C type */")
            else:
                self._output.append(f"typedef struct {name} {name};")
        if self._type_info.opaque_records:
            self._output.append("")

        self._emit_callback_typedefs()

        for name, fields in self._type_info.records.items():
            # Skip if this is a class (handled separately)
            if name in self._type_info.classes:
                continue
            decos = self._type_info.type_decorators.get(name, [])
            deco_lower = [d.lstrip("@").lower() for d in decos]
            packed_attr = " __attribute__((packed))" if "packed" in deco_lower else ""
            self._output.append("typedef struct {")
            for fname, ftype in fields:
                self._output.append(f"    {self._format_decl(ftype, fname)};")
            self._output.append("}" + packed_attr + " " + name + ";")
            self._output.append("")

        # Emit union types
        if self._type_info.unions:
            for name, fields in self._type_info.unions.items():
                decos = self._type_info.type_decorators.get(name, [])
                deco_lower = [d.lstrip("@").lower() for d in decos]
                packed_attr = (
                    " __attribute__((packed))" if "packed" in deco_lower else ""
                )
                self._output.append(f"/* Union: {name} */")
                self._output.append("typedef union {")
                for fname, ftype in fields:
                    self._output.append(f"    {self._format_decl(ftype, fname)};")
                self._output.append("}" + packed_attr + " " + name + ";")
                self._output.append("")

        # Emit class structs
        for class_name, class_info in self._type_info.classes.items():
            class_fields, *_class_rest = class_info
            self._output.append(f"/* Class: {class_name} */")
            self._output.append("typedef struct {")
            for field_tuple in class_fields:
                _visibility, fname, ftype = field_tuple
                self._output.append(f"    {self._format_decl(ftype, fname)};")
                if is_string_type(ftype):
                    self._output.append(f"    int64_t {string_len_field_name(fname)};")
                if is_auto_owned_field_type(ftype, self._type_info.classes):
                    self._output.append(f"    int {owned_field_flag_name(fname)};")
            self._output.append("} " + class_name + ";")
            self._output.append("")

    def _emit_callback_typedefs(self) -> None:
        """Emit C function-pointer typedefs for callback aliases."""
        emitted = False
        for name, target in self._type_info.callback_aliases.items():
            if not is_callback_type(target):
                continue
            params, ret_type, decorators = callback_parts(target)
            ret_c = self._ailang_type_to_c(parsed_type_to_str(ret_type))
            callconv = c_callconv_macro(normalized_decorators(decorators))
            c_params = []
            for index, item in enumerate(params):
                raw_name, raw_type = item
                pname = raw_name if raw_name else f"arg{index}"
                ptype = parsed_type_to_str(raw_type)
                c_params.append(self._format_decl(ptype, pname))
            params_text = ", ".join(c_params) if c_params else "void"
            self._output.append(f"typedef {ret_c} ({callconv}*{name})({params_text});")
            emitted = True
        if emitted:
            self._output.append("")

    def _format_method_param(self, param: Any) -> str:
        """Format a single method parameter for C declaration."""
        if isinstance(param, tuple):
            if len(param) > 1:
                pname, ptype, *_rest = param
            else:
                (pname,) = param
                ptype = "int"
            return self._format_decl(ptype, pname)
        return f"int64_t {param}"

    def _emit_class_method_forward_decls(self, node: A.ClassDef) -> None:
        """Emit forward declarations for class methods."""
        for method in node.methods:
            params = f"{node.name} *self"
            if method.params:
                param_strs = []
                for p in method.params:
                    param_strs.append(self._format_method_param(p))
                    if isinstance(p, tuple) and len(p) >= 2 and is_string_type(p[1]):
                        param_strs.append(
                            f"int64_t {string_len_param_name(param_name(p))}"
                        )
                    if is_auto_owned_param(p, self._type_info.classes):
                        param_strs.append(f"int {owned_param_flag_name(param_name(p))}")
                params += ", " + ", ".join(param_strs)
            ret_type = self._get_return_type(method)
            method_name = "destructor" if method.name.startswith("~") else method.name
            func_name = f"{node.name}_{method_name}"
            self._output.append(f"{ret_type} {func_name}({params});")
        # Forward-declare the `Class_new` wrapper so cross-class
        # instantiation (A's init calling `new B(...)` etc.) compiles
        # regardless of the order classes appear in the source.
        param_decl, _ = self._class_new_signature(node)
        self._output.append(f"static {node.name} *{node.name}_new({param_decl});")
        # Forward-declare the auto-generated destructor stub when the user
        # did NOT define one. Methods including `~ClassName` already get
        # forward-decl'd via the loop above; the auto-stub doesn't.
        if not any(m.name.startswith("~") for m in node.methods):
            self._output.append(
                f"static void {node.name}_destructor({node.name} *self);"
            )

    def _emit_forward_declarations(self, nodes: List[A.ASTNode]) -> None:
        """Emit forward declarations for user functions, extern fn, and template-defined functions."""
        has_funcs = False
        # Emit extern var declarations first
        for node in nodes:
            if isinstance(node, A.ExternVar):
                if not has_funcs:
                    self._output.append("/* Forward declarations */")
                    has_funcs = True
                ctype = self._ailang_type_to_c(node.var_type)
                self._output.append(f"extern {ctype} {node.name};")
        # Emit extern fn declarations first
        for node in nodes:
            if isinstance(node, A.ExternFn):
                decorators = normalized_decorators(getattr(node, "decorators", []))
                if "header_declared" in decorators:
                    continue
                if not has_funcs:
                    self._output.append("/* Forward declarations */")
                    has_funcs = True
                self._emit_extern_fn_decl(node)
        # Scan template blocks for C function definitions and emit forward declarations
        # This ensures AILang code can call template-defined functions without implicit-declaration warnings
        template_fwd_decls = self._extract_template_function_signatures(nodes)
        for decl in template_fwd_decls:
            if not has_funcs:
                self._output.append("/* Forward declarations */")
                has_funcs = True
            self._output.append(decl)
        for node in nodes:
            if isinstance(node, A.Function):
                if not has_funcs:
                    self._output.append("/* Forward declarations */")
                    has_funcs = True
                params = self._format_params(node.params)
                ret_type = self._get_return_type(node)
                mangled_name = self._mangle_name(node.name)
                c_abi = explicit_c_abi_parts(getattr(node, "decorators", []))
                if c_abi is not None:
                    ret_type, c_params = c_abi
                    params = ", ".join(c_params) if c_params else "void"
                # Special handling for main with cmdline args
                if node.name == "main" and "cmdline" in self._needs.helpers:
                    params = "int argc, char **argv"
                    ret_type = "int"
                # Check for @inline decorator - forward decl must also be static inline
                decorators = normalized_decorators(getattr(node, "decorators", []))
                callconv = c_callconv_macro(decorators)
                if "inline" in decorators:
                    self._output.append(
                        f"static inline {ret_type} {callconv}{mangled_name}({params});"
                    )
                else:
                    self._output.append(
                        f"{ret_type} {callconv}{mangled_name}({params});"
                    )
            elif isinstance(node, A.ClassDef):
                if not has_funcs:
                    self._output.append("/* Forward declarations */")
                    has_funcs = True
                self._emit_class_method_forward_decls(node)
        if has_funcs:
            self._output.append("")

    def _emit_dynamic_collection_typedefs(self) -> None:
        """Forward-emit struct typedefs for dynamic collections so
        user types (records, classes) can reference them by value as
        fields. Always emits all three -- they're tiny, harmless if
        unused, and the alternative is fragile gating that has to
        mirror every place a class field could pick one of these
        types up.

        Has to live in the prologue (BEFORE user-type emission) so
        ``class Foo: arr: array`` finds ``ailang_dyn_array`` already
        declared. The matching FUNCTION definitions live in
        ``RuntimeEmitter`` and emit later, gated on usage.
        """
        self._output.append(
            "/* Dynamic collection struct shapes (used as record/class fields) */"
        )
        self._output.append("typedef struct ailang_dyn_array {")
        self._output.append("    int64_t *data;")
        self._output.append("    int64_t length;")
        self._output.append("    int64_t capacity;")
        self._output.append("} ailang_dyn_array;")
        self._output.append("typedef struct ailang_str_array {")
        self._output.append("    const char **data;")
        self._output.append("    int64_t length;")
        self._output.append("    int64_t capacity;")
        self._output.append("} ailang_str_array;")
        self._output.append(
            "AILANG_UNUSED static void ailang_dyn_array_free(" "ailang_dyn_array *arr);"
        )
        self._output.append(
            "AILANG_UNUSED static void ailang_str_array_free_v2("
            "ailang_str_array *arr);"
        )
        self._output.append("typedef struct ailang_dict_entry ailang_dict_entry;")
        self._output.append("typedef struct ailang_dict ailang_dict;")
        self._output.append("")

    def _extract_template_function_signatures(
        self, nodes: List[A.ASTNode]
    ) -> List[str]:
        """Scan template blocks for C function definitions and return forward declarations.

        This enables AILang code to call functions defined in template blocks
        without implicit-function-declaration warnings, regardless of ordering.
        """
        import re

        decls: List[str] = []
        seen_names: set = set()
        # Pattern matches function definitions at the start of a line (not inside #if/#else)
        # Handles: void func(...) {, int64_t func(...) {, static inline int func(...) {
        func_pattern = re.compile(
            r"^((?:static\s+(?:inline\s+)?)?(?:AILANG_UNUSED\s+)?)"
            r"((?:(?:const\s+)?(?:unsigned\s+)?(?:void|int|int32_t|int64_t|uint32_t|uint64_t"
            r"|float|double|char|short|long|size_t|bool)\s*\*?\s*))"
            r"(\w+)\s*\(([^)]*)\)\s*\{",
            re.MULTILINE,
        )
        c_langs = {"ansi_c", "c", "c99", "c11", "c23"}
        for node in nodes:
            if isinstance(node, A.TemplateBlock) and node.language.lower() in c_langs:
                for m in func_pattern.finditer(node.code):
                    qualifiers = m.group(1).strip()  # "static inline" etc.
                    ret_type = m.group(2).strip()
                    name = m.group(3)
                    params = m.group(4).strip()
                    # Skip static/internal helpers (prefixed with underscore or ttf_)
                    # and platform-specific functions inside #if blocks
                    if name.startswith("_") or name.startswith("ttf_"):
                        continue
                    # Don't duplicate: skip if name matches an AILang function
                    if name in self._type_info.functions or name in seen_names:
                        continue
                    seen_names.add(name)
                    # Preserve static/inline qualifiers to match definition
                    prefix = (qualifiers + " ") if qualifiers else ""
                    decl = f"{prefix}{ret_type} {name}({params});"
                    decls.append(decl)
                    # Register in self._type_info.functions so call-site casting works
                    # Map C types back to AILang type names
                    c_to_ail = {
                        "int64_t": "int",
                        "int32_t": "short",
                        "uint32_t": "short",
                        "void": "void",
                        "float": "float",
                        "double": "double",
                        "char": "short",
                    }
                    param_types = []
                    if params and params != "void":
                        for p in params.split(","):
                            p = p.strip()
                            # Extract the C type (everything before the last word)
                            parts = p.rsplit(None, 1)
                            if len(parts) >= 1:
                                ctype_part, *_name_part = parts
                                ctype = ctype_part.strip().replace("*", "").strip()
                                param_types.append(c_to_ail.get(ctype, "int"))
                    ail_ret = c_to_ail.get(ret_type, "int")
                    if name not in self._type_info.functions:
                        self._type_info.functions[name] = (param_types, ail_ret)
        return decls

    def _emit_template_blocks(self, nodes: List[A.ASTNode]) -> None:
        """Emit template blocks (raw C code)."""
        has_templates = False
        for node in nodes:
            if isinstance(node, A.TemplateBlock) and node.language.lower() in (
                "ansi_c",
                "c",
                "c99",
                "c11",
                "c23",
            ):
                if not has_templates:
                    self._output.append("/* Template blocks (foreign C code) */")
                    has_templates = True
                # Emit the raw C code directly
                for line in node.code.strip().split("\n"):
                    self._output.append(line)
                self._output.append("")
        if has_templates:
            self._output.append("")

    def _emit_cinclude_directives(self, nodes: List[A.ASTNode]) -> None:
        """Emit #include directives from #cinclude statements."""
        has_includes = False
        current_os = os_from_platform()
        seen: set[tuple[str, bool]] = set()
        for node in nodes:
            if isinstance(node, A.CInclude) and target_matches(
                getattr(node, "target_os", None), current_os
            ):
                key = (node.path, bool(node.is_system))
                if key in seen:
                    continue
                seen.add(key)
                if not has_includes:
                    self._output.append("/* User includes (#cinclude) */")
                    has_includes = True
                if node.is_system:
                    self._output.append(f"#include <{node.path}>")
                else:
                    self._output.append(f'#include "{node.path}"')
        if has_includes:
            self._output.append("")

    def _emit_link_directives(self, nodes: List[A.ASTNode]) -> None:
        """Emit #link directives as comments for build tools."""
        current_os = os_from_platform()
        for node in nodes:
            if isinstance(node, A.LinkDirective) and target_matches(
                getattr(node, "target_os", None), current_os
            ):
                self._output.append(f"/* AILANG_LINK: {node.flags} */")

    def _emit_extern_fn_decl(self, node: A.ExternFn) -> None:
        """Emit a C forward declaration for an extern fn."""
        ret_c = self._ailang_type_to_c(node.ret_type)
        parts = []
        for pname, ptype in node.params:
            parts.append(self._format_decl(ptype, pname))
        if node.variadic:
            parts.append("...")
        params_str = ", ".join(parts) if parts else "void"
        # Check for calling convention decorators
        decorators = normalized_decorators(getattr(node, "decorators", []))
        callconv = c_callconv_macro(decorators)
        self._output.append(f"extern {ret_c} {callconv}{node.name}({params_str});")
