/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_RPC_RPC_H
#define MIXTAR_BRIDGE_RPC_RPC_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <netdb.h>

#include "types.h"

typedef struct XDR {
	int mixtar_unused;
} XDR;

#endif /* MIXTAR_BRIDGE_RPC_RPC_H */
