/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_RPC_TYPES_H
#define MIXTAR_BRIDGE_RPC_TYPES_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

typedef int32_t bool_t;

typedef int32_t enum_t;

#ifndef TRUE
#define TRUE 1

#endif

#ifndef FALSE
#define FALSE 0

#endif

#endif /* MIXTAR_BRIDGE_RPC_TYPES_H */
