from __future__ import annotations

try:
    from .cbind_probe_model import *
except ImportError:
    from cbind_probe_model import *

try:
    from .cbind_probe_c import *
except ImportError:
    from cbind_probe_c import *

def generate_ail_bindings(spec: BindingSpec, result: ProbeResult) -> str:
    """Generate deterministic AILang binding text from probe result data."""
    lines = [
        "// Generated by tools/cbind_probe.py. Do not edit by hand.",
        "",
    ]

    for header in spec.headers:
        if header.system:
            lines.append(f"#cinclude <{header.path}>")
        else:
            lines.append(f'#cinclude "{header.path}"')
    for flag in spec.link_flags:
        lines.append(f'#link "{flag}"')
    if spec.headers or spec.link_flags:
        lines.append("")

    for row in result.constants:
        lines.append(f"const int {row['name']} = {int(row['value'])}")
    if result.constants:
        lines.append("")

    for row in result.macros:
        if str(row.get("kind", "constant")) != "constant":
            continue
        lines.append(f"const int {row['name']} = {int(row['value'])}")
    if result.macros:
        lines.append("")

    for row in result.enums:
        lines.append(f"enum {row['name']} then")
        for variant in row.get("variants", []):
            lines.append(f"    {variant['name']} = {int(variant['value'])}")
        lines.append("end")
    if result.enums:
        lines.append("")

    for row in result.records:
        name = str(row["name"])
        c_name = str(row.get("c_name", name))
        if row["kind"] == "opaque":
            if c_name != name:
                lines.append(f'opaque record {name} = "{c_name}"')
            else:
                lines.append(f"opaque record {name}")
        else:
            fields = list(row.get("fields", []))
            lines.append(
                f'extern record {name} = "{c_name}" '
                f"layout size {int(row['size'])} align {int(row['align'])} then"
            )
            for field in fields:
                suffix = ""
                if "bit_width" in field:
                    suffix = (
                        f" bit_width {int(field['bit_width'])}"
                        f" bit_offset {int(field.get('bit_offset', 0))}"
                    )
                lines.append(
                    f"    {field['name']} offset {int(field['offset'])} "
                    f"size {int(field['size'])}{suffix}"
                )
            lines.append("end")
    if result.records:
        lines.append("")

    for row in result.records:
        name_ident = _normalize_identifier(str(row["name"]))
        lines.append(f"const int SIZEOF_{name_ident} = {int(row['size'])}")
        lines.append(f"const int ALIGNOF_{name_ident} = {int(row['align'])}")
        for field in row.get("fields", []):
            field_ident = _normalize_identifier(str(field["name"]))
            lines.append(
                f"const int OFFSETOF_{name_ident}_{field_ident} = {int(field['offset'])}"
            )
            if "bit_width" in field:
                lines.append(
                    f"const int BITWIDTH_{name_ident}_{field_ident} = "
                    f"{int(field['bit_width'])}"
                )
                lines.append(
                    f"const int BITOFFSET_{name_ident}_{field_ident} = "
                    f"{int(field.get('bit_offset', 0))}"
                )
    if result.records:
        lines.append("")

    for row in result.functions:
        for deco in row.get("decorators", []):
            lines.append(f"@{deco}")
        params = [
            f"{param['name']}: {param['type']}" for param in row.get("params", [])
        ]
        if row.get("variadic", False):
            params.append("...")
        params_text = ", ".join(params)
        lines.append(f"extern fn {row['name']}({params_text}): {row['return_type']}")
        lines.append("")

    for row in result.wrappers:
        for deco in row.get("decorators", []):
            lines.append(f"@{deco}")
        params = [
            f"{param['name']}: {param['type']}" for param in row.get("params", [])
        ]
        params_text = ", ".join(params)
        lines.append(f"extern fn {row['name']}({params_text}): {row['return_type']}")
        lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)
def _default_output_path(spec_path: Path, suffix: str) -> Path:
    return spec_path.with_suffix(suffix)
def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("spec", type=Path, help="JSON binding probe spec")
    parser.add_argument(
        "--json-out",
        type=Path,
        default=None,
        help="output JSON probe payload (default: <spec>.probe.json)",
    )
    parser.add_argument(
        "--ail-out",
        type=Path,
        default=None,
        help="output generated AIL binding file (default: <spec>.bindings.ail)",
    )
    parser.add_argument(
        "--c-out",
        type=Path,
        default=None,
        help="output generated C assertions/wrappers (default: <spec>.bindings.c)",
    )
    parser.add_argument(
        "--print-json",
        action="store_true",
        help="print JSON payload to stdout",
    )
    parser.add_argument(
        "--compiler",
        default=None,
        help="force compiler executable (default: auto gcc/clang)",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=None,
        help="keep temporary probe files in this directory",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=PROBE_TIMEOUT_SECONDS,
        help="compile/run timeout in seconds",
    )
    args = parser.parse_args()

    try:
        spec = load_binding_spec(args.spec)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"Error: failed to load binding spec: {exc}")
        return 1

    result = probe_binding_spec(
        spec,
        compiler=args.compiler,
        timeout_seconds=max(1, int(args.timeout_seconds)),
        work_dir=args.work_dir,
    )

    json_out = args.json_out or _default_output_path(args.spec, ".probe.json")
    ail_out = args.ail_out or _default_output_path(args.spec, ".bindings.ail")
    c_out = args.c_out or _default_output_path(args.spec, ".bindings.c")
    json_out = json_out.resolve()
    ail_out = ail_out.resolve()
    c_out = c_out.resolve()

    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(result.to_json() + "\n", encoding="utf-8")

    if result.ok:
        ail_out.parent.mkdir(parents=True, exist_ok=True)
        ail_out.write_text(generate_ail_bindings(spec, result), encoding="utf-8")
        if (
            result.records
            or result.wrappers
            or result.constants
            or result.macros
            or result.enums
        ):
            c_out.parent.mkdir(parents=True, exist_ok=True)
            c_out.write_text(generate_c_binding_unit(spec, result), encoding="utf-8")
        if args.print_json:
            print(result.to_json())
        else:
            print(f"cbind probe: ok ({result.compiler})")
            print(f"json: {json_out}")
            print(f"ail:  {ail_out}")
            if (
                result.records
                or result.wrappers
                or result.constants
                or result.macros
                or result.enums
            ):
                print(f"c:    {c_out}")
        return 0

    if args.print_json:
        print(result.to_json())
    else:
        print("cbind probe: failed")
        print(f"json: {json_out}")
        for err in result.errors:
            print(f"error: {err}")
    return 1

__all__ = [name for name in globals() if not name.startswith("__")]
