/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_CASPER_CAP_NET_H
#define MIXTAR_BRIDGE_CASPER_CAP_NET_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <netdb.h>

#include <sys/socket.h>

#include <libcasper.h>

#define CAPNET_NAME2ADDR 0x01

#define CAPNET_CONNECTDNS 0x02

struct mixtar_cap_net_limit {
    int unused;
};

typedef struct mixtar_cap_net_limit cap_net_limit_t;

cap_net_limit_t * cap_net_limit_init(cap_channel_t * channel, int flags);

int cap_net_limit_name2addr_family(cap_net_limit_t * limit, const int * families, int count);

int cap_net_limit(cap_net_limit_t * limit);

static inline int
cap_getaddrinfo(cap_channel_t * channel, const char * node, const char * service, const struct addrinfo * hints, struct addrinfo ** res)
{
    (void)channel;
    return getaddrinfo(node, service, hints, res);
}

static inline int
cap_connect(cap_channel_t * channel, int fd, const struct sockaddr * addr, socklen_t len)
{
    (void)channel;
    return connect(fd, addr, len);
}

#endif /* MIXTAR_BRIDGE_CASPER_CAP_NET_H */
