/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_CAPSICUM_H
#define MIXTAR_BRIDGE_SYS_CAPSICUM_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <stdarg.h>

#define CAP_READ 0x0001ULL

#define CAP_WRITE 0x0002ULL

#define CAP_FSTAT 0x0004ULL

#define CAP_FCNTL 0x0008ULL

#define CAP_SEEK 0x0010ULL

#define CAP_CONNECT 0x0020ULL

#define CAP_SHUTDOWN 0x0040ULL

struct mixtar_cap_rights {
    unsigned long long bits;
};

typedef struct mixtar_cap_rights cap_rights_t;

static inline cap_rights_t *
cap_rights_init(cap_rights_t * rights, ...)
{
    if (rights != 0)
    rights->bits = 0;
    return rights;
}

static inline cap_rights_t *
cap_rights_clear(cap_rights_t * rights, ...)
{
    return rights;
}

#endif /* MIXTAR_BRIDGE_SYS_CAPSICUM_H */
