/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_MAC_H
#define MIXTAR_BRIDGE_SYS_MAC_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <errno.h>

#include <stdlib.h>

#include <string.h>

typedef char * mac_t;

int mac_prepare_file_label(mac_t * label);

int mac_get_file(const char * path, mac_t label);

int mac_get_link(const char * path, mac_t label);

int mac_to_text(mac_t label, char ** text);

int mac_free(void * label);

#endif /* MIXTAR_BRIDGE_SYS_MAC_H */
