#!/usr/bin/env python3
"""Linux-native byte probe for POSIX printf output.

The text-based shell suites cannot safely prove NUL output because Python text
decoding and Markdown reports hide byte differences. This probe runs inside
WSL/Linux and compares raw stdout bytes from msh against Linux /bin/sh.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


RUN_TIMEOUT_SECONDS = 30
STATUS_RE = re.compile(rb"status=(-?\d+)\r?\n?$")


@dataclass(frozen=True)
class ProbeCase:
    name: str
    script: str


@dataclass(frozen=True)
class RunResult:
    status: int
    stdout: bytes
    stderr: bytes


def run_cmd(argv: list[str], cwd: Path) -> subprocess.CompletedProcess[bytes]:
    try:
        return subprocess.run(
            argv,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,
            timeout=RUN_TIMEOUT_SECONDS,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout if isinstance(exc.stdout, bytes) else b""
        stderr = exc.stderr if isinstance(exc.stderr, bytes) else b""
        stderr += f"\ntimeout after {RUN_TIMEOUT_SECONDS}s".encode()
        return subprocess.CompletedProcess(argv, 124, stdout, stderr)


def parse_msh(proc: subprocess.CompletedProcess[bytes]) -> RunResult:
    match = STATUS_RE.search(proc.stdout)
    if match is not None:
        status = int(match.group(1).decode("ascii"))
        return RunResult(status, proc.stdout[: match.start()], proc.stderr)
    return RunResult(proc.returncode, proc.stdout, proc.stderr)


def run_msh(msh: Path, script: str, cwd: Path) -> RunResult:
    return parse_msh(run_cmd([str(msh), "eval", script], cwd))


def run_sh(script: str, cwd: Path) -> RunResult:
    script_path = cwd / "case.sh"
    script_path.write_text(script, encoding="utf-8", newline="\n")
    proc = run_cmd(["/bin/sh", str(script_path)], cwd)
    return RunResult(proc.returncode, proc.stdout, proc.stderr)


def cases() -> list[ProbeCase]:
    return [
        ProbeCase("printf percent-c missing emits nul", "printf '<%c><%c>\\n' A"),
        ProbeCase("printf percent-c empty emits nul", "printf '<%c>\\n' ''"),
        ProbeCase("printf percent-c width counts nul", "printf '<%2c>\\n' ''"),
        ProbeCase("printf format octal nul", "printf 'A\\000B\\n'"),
        ProbeCase("printf percent-b octal nul", "printf '%b\\n' 'A\\000B'"),
        ProbeCase("printf dle byte is not escape-corrupted", "printf 'A\\020B\\n'"),
        ProbeCase(
            "printf nul through redirection",
            "printf '<%c>' '' > out.bin; wc -c < out.bin",
        ),
        ProbeCase(
            "printf nul through external pipeline",
            "printf '<%c>' '' | wc -c",
        ),
    ]


def bytes_cell(value: bytes) -> dict[str, object]:
    return {
        "hex": value.hex(),
        "repr": repr(value),
        "length": len(value),
    }


def run_case(msh: Path, case: ProbeCase, root: Path) -> dict[str, object]:
    case_root = root / case.name.replace(" ", "-")
    case_root.mkdir()
    msh_result = run_msh(msh, case.script, case_root)
    ref = run_sh(case.script, case_root)
    matches = (
        msh_result.status == ref.status
        and msh_result.stdout == ref.stdout
        and msh_result.stderr == ref.stderr
    )
    return {
        "name": case.name,
        "script": case.script,
        "matches": matches,
        "msh": {
            "status": msh_result.status,
            "stdout": bytes_cell(msh_result.stdout),
            "stderr": bytes_cell(msh_result.stderr),
        },
        "sh": {
            "status": ref.status,
            "stdout": bytes_cell(ref.stdout),
            "stderr": bytes_cell(ref.stderr),
        },
    }


def write_reports(rows: list[dict[str, object]], json_path: Path, md_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    total = len(rows)
    matches = sum(1 for row in rows if row["matches"] is True)
    lines = [
        "# msh Linux Printf Byte Probe",
        "",
        "Generated by `msh_linux_printf_byte_probe.py` against Linux `/bin/sh`.",
        "",
        f"- Overall: `{matches}/{total}`",
        "",
        "## Mismatches",
        "",
    ]
    mismatches = [row for row in rows if row["matches"] is not True]
    if not mismatches:
        lines.extend(["No mismatches.", ""])
    for row in mismatches:
        msh = row["msh"]
        sh = row["sh"]
        lines.extend(
            [
                f"### {row['name']}",
                "",
                "```sh",
                str(row["script"]).rstrip(),
                "```",
                "",
                f"- msh: status `{msh['status']}`, stdout hex `{msh['stdout']['hex']}`, stderr hex `{msh['stderr']['hex']}`",
                f"- sh: status `{sh['status']}`, stdout hex `{sh['stdout']['hex']}`, stderr hex `{sh['stderr']['hex']}`",
                "",
            ]
        )
    md_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run Linux-native printf byte probe.")
    parser.add_argument("--msh", required=True, type=Path)
    parser.add_argument("--json-report", type=Path, default=Path("Server/Generated/reports/msh-linux-printf-byte.json"))
    parser.add_argument("--report", type=Path, default=Path("Server/Generated/reports/msh-linux-printf-byte.md"))
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    if os.name == "nt":
        print("msh_linux_printf_byte_probe.py must run on Linux/WSL", file=sys.stderr)
        return 2
    msh = args.msh.resolve()
    if not msh.exists():
        print(f"msh executable not found: {msh}", file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory(prefix="msh-linux-printf-byte-") as raw:
        root = Path(raw)
        rows = [run_case(msh, case, root) for case in cases()]

    write_reports(rows, args.json_report, args.report)
    total = len(rows)
    matches = sum(1 for row in rows if row["matches"] is True)
    print(f"msh linux printf byte probe: {matches}/{total} match /bin/sh")
    if args.strict and matches != total:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
