#!/usr/bin/env python3
"""Generate a broader POSIX-style msh stress suite.

The output is intentionally ordinary .sh files so the existing
`msh_posix_suite.py` runner remains the only comparison engine.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from msh_posix_stress_cases import cases, write_case


MSH_DIR = Path(__file__).resolve().parents[1]
DEFAULT_SUITE = MSH_DIR / "suites" / "posix-stress"


def write_readme(root: Path, count: int) -> None:
    text = f"""# msh posix-stress suite

Generated by `tools/msh_generate_posix_stress_suite.py`.

This suite is broader than `posix-core` and remains an executable audit aid,
not a formal POSIX certification corpus.

Cases generated: `{count}`.
"""
    root.mkdir(parents=True, exist_ok=True)
    (root / "README.md").write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the msh POSIX stress suite.")
    parser.add_argument("--suite", type=Path, default=DEFAULT_SUITE)
    parser.add_argument("--clean", action="store_true", default=True)
    args = parser.parse_args()
    root = args.suite.resolve()
    if args.clean and root.exists():
        shutil.rmtree(root)
    generated = cases()
    for case in generated:
        write_case(root, case)
    write_readme(root, len(generated))
    print(f"generated {len(generated)} POSIX stress cases at {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
