/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_CASPER_CAP_FILEARGS_H
#define MIXTAR_BRIDGE_CASPER_CAP_FILEARGS_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <fcntl.h>

#include <limits.h>

#include <stdlib.h>

#include <unistd.h>

#include <sys/capsicum.h>

#include <libcasper.h>

#define FA_OPEN 0x01

#define FA_REALPATH 0x02

struct mixtar_fileargs {
    int flags;
};

typedef struct mixtar_fileargs fileargs_t;

fileargs_t * fileargs_cinit(cap_channel_t * casper, int argc, char ** argv, int oflags, mode_t mode, cap_rights_t * rights, int flags);

static inline int
fileargs_open(fileargs_t * fa, const char * path)
{
    (void)fa;
    return open(path, O_RDONLY);
}

static inline char *
fileargs_realpath(fileargs_t * fa, const char * path, char * resolved)
{
    (void)fa;
    return realpath(path, resolved);
}

#endif /* MIXTAR_BRIDGE_CASPER_CAP_FILEARGS_H */
