/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_NETINET_IF_ETHER_H
#define MIXTAR_BRIDGE_NETINET_IF_ETHER_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include_next <netinet/if_ether.h>

#include <netinet/ether.h>

#endif /* MIXTAR_BRIDGE_NETINET_IF_ETHER_H */
