/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_IMSG_H
#define MIXTAR_BRIDGE_IMSG_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include "../../OpenBSD/src/lib/libutil/imsg.h"

#endif /* MIXTAR_BRIDGE_IMSG_H */
