/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_UTIL_H
#define MIXTAR_BRIDGE_UTIL_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <errno.h>
#include <pwd.h>
#include <sys/types.h>

#include "libutil.h"

#include "mixtar_bridge_compat.h"

#ifndef MIXTAR_BRIDGE_NO_LOGOUT_SHIM
static inline int
logout(const char *line)
{
	(void)line;
	return 0;
}
#endif

static inline struct passwd *
getpwnam_shadow(const char *name)
{
	return getpwnam(name);
}

static inline int
crypt_checkpass(const char *password, const char *hash)
{
	(void)password;
	(void)hash;
	errno = EPERM;
	return -1;
}

static inline int
crypt_newhash(const char *password, const char *pref, char *hash, size_t hashlen)
{
	(void)pref;
	if (password == NULL || hash == NULL || hashlen == 0) {
		errno = EINVAL;
		return -1;
	}
	if (snprintf(hash, hashlen, "%s", password) >= (int)hashlen) {
		errno = ENAMETOOLONG;
		return -1;
	}
	return 0;
}

static inline int
login_fbtab(const char *tty, uid_t uid, gid_t gid)
{
	(void)tty;
	(void)uid;
	(void)gid;
	return 0;
}

#ifdef MIXTAR_VIPW_COMPAT
#include <err.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>

#ifndef _PATH_MASTERPASSWD
#define _PATH_MASTERPASSWD "/tmp/mixtar-vipw-master.passwd"
#endif
#ifndef _PATH_MASTERPASSWD_LOCK
#define _PATH_MASTERPASSWD_LOCK "/tmp/mixtar-vipw-master.passwd.lock"
#endif
#ifndef _PATH_BSHELL
#define _PATH_BSHELL "/bin/sh"
#endif
#ifndef _PATH_PWD_MKDB
#define _PATH_PWD_MKDB "/bin/true"
#endif

static inline void
pw_init(void)
{
	int fd;

	fd = open(_PATH_MASTERPASSWD, O_WRONLY | O_CREAT | O_APPEND, 0600);
	if (fd >= 0)
		(void)close(fd);
}

static inline int
pw_lock(int force)
{
	(void)force;
	return open(_PATH_MASTERPASSWD_LOCK, O_RDWR | O_CREAT | O_TRUNC, 0600);
}

static inline void
pw_edit(int notset, char *filename)
{
	(void)notset;
	(void)filename;
}

static inline int
pw_mkdb(char *username, int flags)
{
	(void)username;
	(void)flags;
	return 0;
}

static inline void
pw_prompt(void)
{
}

static inline void
pw_error(const char *name, int use_errno, int eval)
{
	if (name != NULL) {
		if (use_errno)
			warn("%s", name);
		else
			warnx("%s", name);
	}
	(void)unlink(_PATH_MASTERPASSWD_LOCK);
	exit(eval);
}
#endif

#endif /* MIXTAR_BRIDGE_UTIL_H */
