/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_CPUSET_H
#define MIXTAR_BRIDGE_SYS_CPUSET_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <ctype.h>
#include <errno.h>
#include <sched.h>
#include <stdlib.h>
#include <string.h>

#define CPU_LEVEL_ROOT 1

#define CPU_LEVEL_CPUSET 2

#define CPU_LEVEL_WHICH 3

#define CPU_WHICH_TID 1

#define CPU_WHICH_PID 2

#define CPU_WHICH_CPUSET 3

#define CPU_WHICH_IRQ 4

#define CPU_WHICH_JAIL 5

#define CPU_WHICH_DOMAIN 6

typedef int cpulevel_t;

typedef int cpuwhich_t;

typedef int cpusetid_t;

typedef int lwpid_t;

typedef cpu_set_t cpuset_t;

struct bitset {
	unsigned long __bits[sizeof(cpu_set_t) / sizeof(unsigned long)];
};

#define BIT_ISSET(size, bit, set) \
	(((void)(size)), CPU_ISSET((bit), (cpu_set_t *)(void *)(set)))

static inline pid_t
mixtar_cpuset_linux_target(cpuwhich_t which, id_t id)
{
	if ((pid_t)id < 0)
		return 0;
	if (which == CPU_WHICH_PID || which == CPU_WHICH_TID)
		return (pid_t)id;
	errno = ENOTSUP;
	return -1;
}

static inline void
cpuset_parselist(const char *list, cpuset_t *mask)
{
	const char *p = list;

	CPU_ZERO(mask);
	while (p != NULL && *p != '\0') {
		char *end = NULL;
		long start;
		long stop;

		while (*p == ',' || isspace((unsigned char)*p))
			p++;
		if (*p == '\0')
			break;
		start = strtol(p, &end, 10);
		if (end == p || start < 0)
			break;
		stop = start;
		p = end;
		if (*p == '-') {
			p++;
			stop = strtol(p, &end, 10);
			if (end == p || stop < start)
				break;
			p = end;
		}
		for (long cpu = start; cpu <= stop && cpu < CPU_SETSIZE; cpu++)
			CPU_SET((int)cpu, mask);
		if (*p == ',')
			p++;
	}
}

static inline int
cpuset_getaffinity(cpulevel_t level, cpuwhich_t which, id_t id, size_t setsize, cpuset_t * mask)
{
	pid_t target;

	(void)level;
	target = mixtar_cpuset_linux_target(which, id);
	if (target < 0)
		return -1;
	return sched_getaffinity(target, setsize, mask);
}

static inline int
cpuset_setaffinity(cpulevel_t level, cpuwhich_t which, id_t id,
    size_t setsize, const cpuset_t *mask)
{
	pid_t target;

	(void)level;
	target = mixtar_cpuset_linux_target(which, id);
	if (target < 0)
		return -1;
	return sched_setaffinity(target, setsize, mask);
}

static inline int
cpuset(cpusetid_t *setid)
{
	if (setid != NULL)
		*setid = 0;
	return 0;
}

static inline int
cpuset_getid(cpulevel_t level, cpuwhich_t which, id_t id, cpusetid_t *setid)
{
	(void)level;
	(void)which;
	(void)id;
	if (setid == NULL) {
		errno = EINVAL;
		return -1;
	}
	*setid = 0;
	return 0;
}

static inline int
cpuset_setid(cpuwhich_t which, id_t id, cpusetid_t setid)
{
	(void)which;
	(void)id;
	if (setid == 0)
		return 0;
	errno = ENOTSUP;
	return -1;
}

#endif /* MIXTAR_BRIDGE_SYS_CPUSET_H */
