/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_CAPSICUM_HELPERS_H
#define MIXTAR_BRIDGE_CAPSICUM_HELPERS_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include "sys/capsicum.h"

int caph_limit_stdio(void);

int caph_enter(void);

void caph_cache_catpages(void);

int caph_enter_casper(void);

int caph_rights_limit(int fd, const cap_rights_t * rights);

#endif /* MIXTAR_BRIDGE_CAPSICUM_HELPERS_H */
