/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_LIBCASPER_H
#define MIXTAR_BRIDGE_LIBCASPER_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

typedef struct mixtar_cap_channel cap_channel_t;

struct mixtar_cap_channel {
    int unused;
};

cap_channel_t * cap_init(void);

int cap_close(cap_channel_t * channel);

cap_channel_t * cap_service_open(cap_channel_t * channel, const char * name);

#endif /* MIXTAR_BRIDGE_LIBCASPER_H */
