/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS__NULL_H
#define MIXTAR_BRIDGE_SYS__NULL_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#endif /* MIXTAR_BRIDGE_SYS__NULL_H */
