/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_ACL_H
#define MIXTAR_BRIDGE_SYS_ACL_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <errno.h>

#include <stdio.h>

#include <stdlib.h>

#include <string.h>

#include <sys/stat.h>

#include <unistd.h>

#define _PC_ACL_NFS4 20001

#define _PC_ACL_EXTENDED 20002

#define ACL_TYPE_ACCESS 1

#define ACL_TYPE_DEFAULT 3

#define ACL_TYPE_NFS4 2

#define ACL_BRAND_POSIX 1

#define ACL_BRAND_NFS4 2

#define ACL_BRAND_UNKNOWN 3

#define ACL_EXTENDED 1

#define ACL_TEXT_APPEND_ID 0x0001

#define ACL_TEXT_NUMERIC_IDS 0x0002

#define ACL_TEXT_VERBOSE 0x0004

#define ACL_UNDEFINED_TAG 0
#define ACL_USER_OBJ 1
#define ACL_USER 2
#define ACL_GROUP_OBJ 3
#define ACL_GROUP 4
#define ACL_MASK 5
#define ACL_OTHER 6
#define ACL_EVERYONE 7

#define ACL_FIRST_ENTRY 0
#define ACL_NEXT_ENTRY 1
#define ACL_MAX_ENTRIES 32

#define ACL_ENTRY_INHERIT_ONLY 0x0001
#define ACL_ENTRY_FILE_INHERIT 0x0002
#define ACL_ENTRY_DIRECTORY_INHERIT 0x0004
#define ACL_ENTRY_NO_PROPAGATE_INHERIT 0x0008

typedef void * acl_t;

typedef int acl_type_t;

typedef struct mixtar_acl_entry * acl_entry_t;
typedef unsigned int acl_permset_t;
typedef int acl_tag_t;
typedef unsigned int acl_flagset_t;
typedef int acl_entry_type_t;

struct mixtar_acl_entry {
	acl_tag_t tag;
	uid_t qualifier;
	acl_permset_t perm;
	acl_flagset_t flags;
	acl_entry_type_t entry_type;
};

struct mixtar_acl_mode {
	mode_t mode;
	int brand;
	int count;
	int cursor;
	struct mixtar_acl_entry entries[ACL_MAX_ENTRIES];
};

acl_t acl_get_fd_np(int fd, acl_type_t type);

acl_t acl_get_link_np(const char * path, acl_type_t type);

int acl_set_fd_np(int fd, acl_t acl, acl_type_t type);

int acl_is_trivial_np(acl_t acl, int * trivial);

int acl_is_trivial(acl_t acl, int * trivial);

int acl_free(void * obj);

int acl_supported(const char * path, acl_type_t type);

static inline void
mixtar_acl_perm(char *out, mode_t mode, mode_t read_bit, mode_t write_bit,
    mode_t exec_bit)
{
	out[0] = (mode & read_bit) ? 'r' : '-';
	out[1] = (mode & write_bit) ? 'w' : '-';
	out[2] = (mode & exec_bit) ? 'x' : '-';
	out[3] = '\0';
}

static inline acl_permset_t
mixtar_acl_perm_from_mode(mode_t mode, mode_t read_bit, mode_t write_bit,
    mode_t exec_bit)
{
	acl_permset_t perm = 0;

	if (mode & read_bit)
		perm |= 4;
	if (mode & write_bit)
		perm |= 2;
	if (mode & exec_bit)
		perm |= 1;
	return perm;
}

static inline mode_t
mixtar_acl_mode_from_perm(acl_permset_t perm, mode_t read_bit,
    mode_t write_bit, mode_t exec_bit)
{
	mode_t mode = 0;

	if (perm & 4)
		mode |= read_bit;
	if (perm & 2)
		mode |= write_bit;
	if (perm & 1)
		mode |= exec_bit;
	return mode;
}

static inline acl_permset_t
mixtar_acl_perm_from_text(const char *text)
{
	acl_permset_t perm = 0;

	if (text == NULL)
		return 0;
	for (int i = 0; text[i] != '\0' && text[i] != ',' &&
	    text[i] != '\n'; i++) {
		if (text[i] == 'r')
			perm |= 4;
		else if (text[i] == 'w')
			perm |= 2;
		else if (text[i] == 'x')
			perm |= 1;
	}
	return perm;
}

static inline int
mixtar_acl_add_entry(struct mixtar_acl_mode *acl, acl_tag_t tag,
    acl_permset_t perm)
{
	struct mixtar_acl_entry *entry;

	if (acl == NULL || acl->count >= ACL_MAX_ENTRIES) {
		errno = ENOMEM;
		return -1;
	}
	entry = &acl->entries[acl->count++];
	memset(entry, 0, sizeof(*entry));
	entry->tag = tag;
	entry->perm = perm;
	return 0;
}

static inline void
mixtar_acl_fill_from_mode(struct mixtar_acl_mode *acl, mode_t mode)
{
	acl->mode = mode;
	acl->brand = ACL_BRAND_POSIX;
	acl->count = 0;
	acl->cursor = 0;
	mixtar_acl_add_entry(acl, ACL_USER_OBJ,
	    mixtar_acl_perm_from_mode(mode, S_IRUSR, S_IWUSR, S_IXUSR));
	mixtar_acl_add_entry(acl, ACL_GROUP_OBJ,
	    mixtar_acl_perm_from_mode(mode, S_IRGRP, S_IWGRP, S_IXGRP));
	mixtar_acl_add_entry(acl, ACL_OTHER,
	    mixtar_acl_perm_from_mode(mode, S_IROTH, S_IWOTH, S_IXOTH));
}

static inline acl_t
acl_from_mode_np(mode_t mode)
{
	struct mixtar_acl_mode *acl = malloc(sizeof(*acl));

	if (acl == NULL)
		return NULL;
	mixtar_acl_fill_from_mode(acl, mode);
	return (acl_t)acl;
}

static inline acl_t
acl_init(int count)
{
	struct mixtar_acl_mode *acl;

	(void)count;
	acl = calloc(1, sizeof(*acl));
	if (acl == NULL)
		return NULL;
	acl->brand = ACL_BRAND_POSIX;
	return (acl_t)acl;
}

static inline acl_t
acl_dup(acl_t src)
{
	struct mixtar_acl_mode *acl_src = (struct mixtar_acl_mode *)src;
	struct mixtar_acl_mode *acl_dst;

	if (acl_src == NULL) {
		errno = EINVAL;
		return NULL;
	}
	acl_dst = malloc(sizeof(*acl_dst));
	if (acl_dst == NULL)
		return NULL;
	memcpy(acl_dst, acl_src, sizeof(*acl_dst));
	acl_dst->cursor = 0;
	return (acl_t)acl_dst;
}

static inline acl_t
acl_get_file(const char *path, acl_type_t type)
{
	struct stat sb;

	if (type == ACL_TYPE_DEFAULT) {
		errno = EOPNOTSUPP;
		return NULL;
	}
	if (stat(path, &sb) != 0)
		return NULL;
	return acl_from_mode_np(sb.st_mode);
}

static inline acl_t
acl_from_text(const char *text)
{
	struct mixtar_acl_mode *acl;
	char *copy;
	char *line;
	char *saveptr = NULL;

	if (text == NULL) {
		errno = EINVAL;
		return NULL;
	}
	acl = calloc(1, sizeof(*acl));
	if (acl == NULL)
		return NULL;
	acl->brand = ACL_BRAND_POSIX;
	copy = strdup(text);
	if (copy == NULL) {
		free(acl);
		return NULL;
	}
	for (line = strtok_r(copy, ",\n", &saveptr); line != NULL;
	    line = strtok_r(NULL, ",\n", &saveptr)) {
		while (*line == ' ' || *line == '\t')
			line++;
		if (strncmp(line, "user::", 6) == 0 ||
		    strncmp(line, "u::", 3) == 0) {
			const char *perm = strchr(line, ':');
			perm = perm != NULL ? strchr(perm + 1, ':') : NULL;
			if (perm != NULL)
				mixtar_acl_add_entry(acl, ACL_USER_OBJ,
				    mixtar_acl_perm_from_text(perm + 1));
		} else if (strncmp(line, "group::", 7) == 0 ||
		    strncmp(line, "g::", 3) == 0) {
			const char *perm = strchr(line, ':');
			perm = perm != NULL ? strchr(perm + 1, ':') : NULL;
			if (perm != NULL)
				mixtar_acl_add_entry(acl, ACL_GROUP_OBJ,
				    mixtar_acl_perm_from_text(perm + 1));
		} else if (strncmp(line, "other::", 7) == 0 ||
		    strncmp(line, "o::", 3) == 0) {
			const char *perm = strchr(line, ':');
			perm = perm != NULL ? strchr(perm + 1, ':') : NULL;
			if (perm != NULL)
				mixtar_acl_add_entry(acl, ACL_OTHER,
				    mixtar_acl_perm_from_text(perm + 1));
		} else if (strncmp(line, "mask::", 6) == 0 ||
		    strncmp(line, "m::", 3) == 0) {
			const char *perm = strchr(line, ':');
			perm = perm != NULL ? strchr(perm + 1, ':') : NULL;
			if (perm != NULL)
				mixtar_acl_add_entry(acl, ACL_MASK,
				    mixtar_acl_perm_from_text(perm + 1));
		}
	}
	free(copy);
	if (acl->count == 0) {
		free(acl);
		errno = EINVAL;
		return NULL;
	}
	return (acl_t)acl;
}

static inline int
acl_get_brand_np(acl_t acl, int *brand)
{
	struct mixtar_acl_mode *mode_acl = (struct mixtar_acl_mode *)acl;

	if (brand == NULL) {
		errno = EINVAL;
		return -1;
	}
	*brand = mode_acl != NULL ? mode_acl->brand : ACL_BRAND_UNKNOWN;
	return 0;
}

static inline int
acl_get_entry(acl_t acl, int entry_id, acl_entry_t *entry)
{
	struct mixtar_acl_mode *mode_acl = (struct mixtar_acl_mode *)acl;

	if (mode_acl == NULL || entry == NULL) {
		errno = EINVAL;
		return -1;
	}
	if (entry_id == ACL_FIRST_ENTRY)
		mode_acl->cursor = 0;
	if (mode_acl->cursor >= mode_acl->count)
		return 0;
	*entry = &mode_acl->entries[mode_acl->cursor++];
	return 1;
}

static inline int
acl_get_tag_type(acl_entry_t entry, acl_tag_t *tag)
{
	if (entry == NULL || tag == NULL) {
		errno = EINVAL;
		return -1;
	}
	*tag = entry->tag;
	return 0;
}

static inline int
acl_get_permset(acl_entry_t entry, acl_permset_t *permset)
{
	if (entry == NULL || permset == NULL) {
		errno = EINVAL;
		return -1;
	}
	*permset = entry->perm;
	return 0;
}

static inline int
acl_set_permset(acl_entry_t entry, acl_permset_t permset)
{
	if (entry == NULL) {
		errno = EINVAL;
		return -1;
	}
	entry->perm = permset;
	return 0;
}

static inline void *
acl_get_qualifier(acl_entry_t entry)
{
	uid_t *qualifier;

	if (entry == NULL) {
		errno = EINVAL;
		return NULL;
	}
	qualifier = malloc(sizeof(*qualifier));
	if (qualifier == NULL)
		return NULL;
	*qualifier = entry->qualifier;
	return qualifier;
}

static inline int
acl_copy_entry(acl_entry_t dst, acl_entry_t src)
{
	if (dst == NULL || src == NULL) {
		errno = EINVAL;
		return -1;
	}
	*dst = *src;
	return 0;
}

static inline int
acl_create_entry(acl_t *acl, acl_entry_t *entry)
{
	struct mixtar_acl_mode *mode_acl;

	if (acl == NULL || *acl == NULL || entry == NULL) {
		errno = EINVAL;
		return -1;
	}
	mode_acl = (struct mixtar_acl_mode *)*acl;
	if (mode_acl->count >= ACL_MAX_ENTRIES) {
		errno = ENOMEM;
		return -1;
	}
	*entry = &mode_acl->entries[mode_acl->count++];
	memset(*entry, 0, sizeof(**entry));
	return 0;
}

static inline int
acl_create_entry_np(acl_t *acl, acl_entry_t *entry, int index)
{
	struct mixtar_acl_mode *mode_acl;

	if (acl == NULL || *acl == NULL || entry == NULL) {
		errno = EINVAL;
		return -1;
	}
	mode_acl = (struct mixtar_acl_mode *)*acl;
	if (mode_acl->count >= ACL_MAX_ENTRIES) {
		errno = ENOMEM;
		return -1;
	}
	if (index < 0 || index > mode_acl->count)
		index = mode_acl->count;
	memmove(&mode_acl->entries[index + 1], &mode_acl->entries[index],
	    (size_t)(mode_acl->count - index) * sizeof(mode_acl->entries[0]));
	mode_acl->count++;
	*entry = &mode_acl->entries[index];
	memset(*entry, 0, sizeof(**entry));
	return 0;
}

static inline int
acl_delete_entry(acl_t acl, acl_entry_t entry)
{
	struct mixtar_acl_mode *mode_acl = (struct mixtar_acl_mode *)acl;

	if (mode_acl == NULL || entry == NULL) {
		errno = EINVAL;
		return -1;
	}
	for (int i = 0; i < mode_acl->count; i++) {
		if (mode_acl->entries[i].tag == entry->tag &&
		    mode_acl->entries[i].qualifier == entry->qualifier) {
			memmove(&mode_acl->entries[i], &mode_acl->entries[i + 1],
			    (size_t)(mode_acl->count - i - 1) *
			    sizeof(mode_acl->entries[0]));
			mode_acl->count--;
			return 0;
		}
	}
	errno = ENOENT;
	return -1;
}

static inline int
acl_delete_entry_np(acl_t acl, int index)
{
	struct mixtar_acl_mode *mode_acl = (struct mixtar_acl_mode *)acl;

	if (mode_acl == NULL || index < 0 || index >= mode_acl->count) {
		errno = EINVAL;
		return -1;
	}
	memmove(&mode_acl->entries[index], &mode_acl->entries[index + 1],
	    (size_t)(mode_acl->count - index - 1) *
	    sizeof(mode_acl->entries[0]));
	mode_acl->count--;
	return 0;
}

static inline int
acl_calc_mask(acl_t *acl)
{
	(void)acl;
	return 0;
}

static inline acl_t
acl_strip_np(acl_t acl, int recalculate_mask)
{
	(void)recalculate_mask;
	return acl_dup(acl);
}

static inline int
acl_get_entry_type_np(acl_entry_t entry, acl_entry_type_t *entry_type)
{
	if (entry == NULL || entry_type == NULL) {
		errno = EINVAL;
		return -1;
	}
	*entry_type = entry->entry_type;
	return 0;
}

static inline int
acl_set_entry_type_np(acl_entry_t entry, acl_entry_type_t entry_type)
{
	if (entry == NULL) {
		errno = EINVAL;
		return -1;
	}
	entry->entry_type = entry_type;
	return 0;
}

static inline int
acl_get_flagset_np(acl_entry_t entry, acl_flagset_t *flagset)
{
	if (entry == NULL || flagset == NULL) {
		errno = EINVAL;
		return -1;
	}
	*flagset = entry->flags;
	return 0;
}

static inline int
acl_set_flagset_np(acl_entry_t entry, acl_flagset_t flagset)
{
	if (entry == NULL) {
		errno = EINVAL;
		return -1;
	}
	entry->flags = flagset;
	return 0;
}

static inline int
acl_get_flag_np(acl_flagset_t flagset, int flag)
{
	return (flagset & (acl_flagset_t)flag) != 0;
}

static inline int
acl_delete_flag_np(acl_flagset_t flagset, int flags)
{
	(void)flagset;
	(void)flags;
	return 0;
}

static inline mode_t
mixtar_acl_to_mode(struct mixtar_acl_mode *acl, mode_t old_mode)
{
	mode_t mode = old_mode & ~(mode_t)0777;
	int have_user = 0;
	int have_group = 0;
	int have_other = 0;

	for (int i = 0; i < acl->count; i++) {
		if (acl->entries[i].tag == ACL_USER_OBJ) {
			mode |= mixtar_acl_mode_from_perm(acl->entries[i].perm,
			    S_IRUSR, S_IWUSR, S_IXUSR);
			have_user = 1;
		} else if (acl->entries[i].tag == ACL_GROUP_OBJ) {
			mode |= mixtar_acl_mode_from_perm(acl->entries[i].perm,
			    S_IRGRP, S_IWGRP, S_IXGRP);
			have_group = 1;
		} else if (acl->entries[i].tag == ACL_OTHER) {
			mode |= mixtar_acl_mode_from_perm(acl->entries[i].perm,
			    S_IROTH, S_IWOTH, S_IXOTH);
			have_other = 1;
		}
	}
	if (!have_user)
		mode |= old_mode & 0700;
	if (!have_group)
		mode |= old_mode & 0070;
	if (!have_other)
		mode |= old_mode & 0007;
	return mode;
}

static inline int
acl_set_file(const char *path, acl_type_t type, acl_t acl)
{
	struct mixtar_acl_mode *mode_acl = (struct mixtar_acl_mode *)acl;
	struct stat sb;

	if (path == NULL || mode_acl == NULL) {
		errno = EINVAL;
		return -1;
	}
	if (type == ACL_TYPE_DEFAULT)
		return 0;
	if (stat(path, &sb) != 0)
		return -1;
	return chmod(path, mixtar_acl_to_mode(mode_acl, sb.st_mode) & 0777);
}

static inline int
acl_set_link_np(const char *path, acl_type_t type, acl_t acl)
{
	return acl_set_file(path, type, acl);
}

static inline int
acl_delete_def_file(const char *path)
{
	(void)path;
	return 0;
}

static inline char *
acl_to_text_np(acl_t acl, ssize_t *len_p, int flags)
{
	struct mixtar_acl_mode *mode_acl = (struct mixtar_acl_mode *)acl;
	char user_perm[4];
	char group_perm[4];
	char other_perm[4];
	char *text;
	int n;

	(void)flags;
	if (mode_acl == NULL) {
		errno = EINVAL;
		return NULL;
	}
	mixtar_acl_perm(user_perm, mode_acl->mode, S_IRUSR, S_IWUSR, S_IXUSR);
	mixtar_acl_perm(group_perm, mode_acl->mode, S_IRGRP, S_IWGRP, S_IXGRP);
	mixtar_acl_perm(other_perm, mode_acl->mode, S_IROTH, S_IWOTH, S_IXOTH);
	n = snprintf(NULL, 0, "user::%s\ngroup::%s\nother::%s\n",
	    user_perm, group_perm, other_perm);
	if (n < 0)
		return NULL;
	text = malloc((size_t)n + 1);
	if (text == NULL)
		return NULL;
	snprintf(text, (size_t)n + 1, "user::%s\ngroup::%s\nother::%s\n",
	    user_perm, group_perm, other_perm);
	if (len_p != NULL)
		*len_p = n;
	return text;
}

#endif /* MIXTAR_BRIDGE_SYS_ACL_H */
