/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_DIRENT_H
#define MIXTAR_BRIDGE_SYS_DIRENT_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <dirent.h>

#endif /* MIXTAR_BRIDGE_SYS_DIRENT_H */
