/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_EVENT_H
#define MIXTAR_BRIDGE_SYS_EVENT_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <errno.h>

#include <stdio.h>

#include <signal.h>

#include <string.h>

#include <time.h>

#include <unistd.h>

#define EVFILT_READ -1

#define EVFILT_VNODE -4

#define EVFILT_PROC -5

#define EVFILT_SIGNAL -6

#define EV_ADD 0x0001

#define EV_ENABLE 0x0004

#define EV_CLEAR 0x0020

#define NOTE_DELETE 0x0001

#define NOTE_WRITE 0x0002

#define NOTE_EXTEND 0x0004

#define NOTE_ATTRIB 0x0008

#define NOTE_LINK 0x0010

#define NOTE_RENAME 0x0020

#define NOTE_REVOKE 0x0040

#define NOTE_TRUNCATE 0x0080

#define NOTE_EXIT 0x80000000U

struct kevent {
    uintptr_t ident;
    short filter;
    unsigned short flags;
    unsigned int fflags;
    intptr_t data;
    void * udata;
};

#define EV_SET(kevp, a, b, c, d, e, f) do { \
    (kevp)->ident = (uintptr_t)(a); \
    (kevp)->filter = (b); \
    (kevp)->flags = (c); \
    (kevp)->fflags = (d); \
    (kevp)->data = (e); \
    (kevp)->udata = (f); \
    } while (0)

#ifndef MIXTAR_PWAIT_COMPAT
int kqueue(void);

int kevent(int kq, const struct kevent * changelist, int nchanges, struct kevent * eventlist, int nevents, const struct timespec * timeout);
#endif

#ifdef MIXTAR_PWAIT_COMPAT
#define MIXTAR_PWAIT_MAX_EVENTS 1024
static pid_t mixtar_pwait_pids[MIXTAR_PWAIT_MAX_EVENTS];
static int mixtar_pwait_pid_count;

static inline int
mixtar_pwait_pid_alive(pid_t pid)
{
	char path[64];
	char statbuf[256];
	FILE *fp;
	char *comm_end;

	if (pid <= 0)
		return 0;
	if (kill(pid, 0) != 0)
		return errno != ESRCH;

	snprintf(path, sizeof(path), "/proc/%d/stat", (int)pid);
	fp = fopen(path, "r");
	if (fp == NULL)
		return 1;
	if (fgets(statbuf, sizeof(statbuf), fp) == NULL) {
		fclose(fp);
		return 1;
	}
	fclose(fp);

	comm_end = strrchr(statbuf, ')');
	if (comm_end != NULL && comm_end[1] == ' ' && comm_end[2] == 'Z')
		return 0;
	return 1;
}

static inline int
kqueue(void)
{
	mixtar_pwait_pid_count = 0;
	return 1;
}

static inline int
kevent(int kq, const struct kevent *changelist, int nchanges,
    struct kevent *eventlist, int nevents, const struct timespec *timeout)
{
	(void)kq;
	(void)timeout;

	if (changelist != NULL && nchanges > 0) {
		for (int i = 0; i < nchanges; i++) {
			if (changelist[i].filter == EVFILT_PROC) {
				pid_t pid = (pid_t)changelist[i].ident;
				if (!mixtar_pwait_pid_alive(pid)) {
					errno = ESRCH;
					return -1;
				}
				if (mixtar_pwait_pid_count >= MIXTAR_PWAIT_MAX_EVENTS) {
					errno = ENOMEM;
					return -1;
				}
				mixtar_pwait_pids[mixtar_pwait_pid_count++] = pid;
			}
		}
		return 0;
	}

	if (eventlist == NULL || nevents <= 0)
		return 0;

	for (;;) {
		for (int i = 0; i < mixtar_pwait_pid_count; i++) {
			pid_t pid = mixtar_pwait_pids[i];
			if (!mixtar_pwait_pid_alive(pid)) {
				EV_SET(&eventlist[0], pid, EVFILT_PROC, 0,
				    NOTE_EXIT, 0, NULL);
				mixtar_pwait_pids[i] =
				    mixtar_pwait_pids[mixtar_pwait_pid_count - 1];
				mixtar_pwait_pid_count--;
				return 1;
			}
		}
		usleep(10000);
	}
}
#endif

#endif /* MIXTAR_BRIDGE_SYS_EVENT_H */
