/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_LIMITS_H
#define MIXTAR_BRIDGE_SYS_LIMITS_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <limits.h>

#endif /* MIXTAR_BRIDGE_SYS_LIMITS_H */
