/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_MALLOC_H
#define MIXTAR_BRIDGE_SYS_MALLOC_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

#include <stdlib.h>

#ifndef MINBUCKET
#define MINBUCKET 4
#endif

#ifndef M_LAST
#define M_LAST 1
#endif

#ifndef INITKMEMNAMES
#define INITKMEMNAMES { "misc" }
#endif

struct kmembuckets {
	unsigned long long kb_calls;
	unsigned long long kb_total;
	unsigned long long kb_totalfree;
	unsigned long long kb_highwat;
	unsigned long long kb_couldfree;
	unsigned long long kb_elmpercl;
};

struct kmemstats {
	long ks_inuse;
	long ks_memuse;
	long ks_maxused;
	long ks_limit;
	unsigned long ks_calls;
	unsigned int ks_limblocks;
	long ks_size;
	long ks_spare;
};

#endif /* MIXTAR_BRIDGE_SYS_MALLOC_H */
