/* Generated by AILang ABI header. Do not edit by hand. */
#ifndef MIXTAR_BRIDGE_SYS_TTY_H
#define MIXTAR_BRIDGE_SYS_TTY_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>

struct tty {
    int dummy;
};

#endif /* MIXTAR_BRIDGE_SYS_TTY_H */
